
/* Offsets for structure NUTkmu3 */
#define NUTKMU3_TIMESTAMP 0
#define NUTKMU3_MAXE	 1
#define NUTKMU3_MAXCOG	 2
#define NUTKMU3_MAXD	 3
#define NUTKMU3_MAXZ	 4
#define NUTKMU3_MAXL	 5
#define NUTKMU3_MAXTF	 6
#define NUTKMU3_SPY_X 7
#define NUTKMU3_SPY_Y 71
#define NUTKMU3_SPY_XCBIT 135
#define NUTKMU3_SPY_YCBIT 141
#define NUTKMU3_SIZE 147

/* Offsets for structure RNDMsummary */
#define RNDMSUMMARY_TYPE 0
#define RNDMSUMMARY_TIMESTAMP 1
#define RNDMSUMMARY_RUN_BURST 2
#define RNDMSUMMARY_RUN 3
#define RNDMSUMMARY_BURST 4
#define RNDMSUMMARY_NUSED 5
#define RNDMSUMMARY_SPSPHASE 6
#define RNDMSUMMARY_MAINPHASE 7
#define RNDMSUMMARY_PDSUSED 8
#define RNDMSUMMARY_TOVRFLW 9
#define RNDMSUMMARY_ROVRFLW 73
#define RNDMSUMMARY_KLMONDNDT 77
#define RNDMSUMMARY_KSMONDNDT 78
#define RNDMSUMMARY_TAGMONDNDT 79
#define RNDMSUMMARY_QXDNDT 80
#define RNDMSUMMARY_AKSDNDT 81
#define RNDMSUMMARY_SIZE 82

/* Offsets for structure L3TRIGhist */
#define L3TRIGHIST_TRIGWORD 0
#define L3TRIGHIST_TSTAMP_DIFF 1
#define L3TRIGHIST_SIZE 2

/* Offsets for structure EVTtimestamp */
#define EVTTIMESTAMP_TIMESTAMP 0
#define EVTTIMESTAMP_SOURCE 1
#define EVTTIMESTAMP_SIZE 2

/* Offsets for structure PMBscaler */
#define PMBSCALER_N 0
#define PMBSCALER_DNDT 1
#define PMBSCALER_SIZE 2

/* Offsets for structure PMBtimeslice */
#define PMBTIMESLICE_CHAN 0
#define PMBTIMESLICE_SIZE 16

/* Offsets for structure TAGhit */
#define TAGHIT_AMPL 0
#define TAGHIT_TIME 1
#define TAGHIT_CHI2 2
#define TAGHIT_STATUS 3
#define TAGHIT_SIZE 4

/* Offsets for structure TAGchannel */
#define TAGCHANNEL_N 0
#define TAGCHANNEL_NHIT 1
#define TAGCHANNEL_HIT 2
#define TAGCHANNEL_SIZE 62

/* Offsets for structure KSMhit */
#define KSMHIT_COUNTER 0
#define KSMHIT_PHEIGHT 1
#define KSMHIT_TIME 2
#define KSMHIT_PDSFLAG 3
#define KSMHIT_SIZE 4

/* Offsets for structure BeamInt */
#define BEAMINT_INTEG2US 0
#define BEAMINT_INTEG15US 1
#define BEAMINT_INTEG30US 2
#define BEAMINT_INTEG60US 3
#define BEAMINT_QUAL2US 4
#define BEAMINT_QUAL15US 5
#define BEAMINT_QUAL30US 6
#define BEAMINT_QUAL60US 7
#define BEAMINT_PACKSAMP 8
#define BEAMINT_SIZE 12

/* Offsets for structure AKScounter */
#define AKSCOUNTER_TIME 0
#define AKSCOUNTER_TIME2 1
#define AKSCOUNTER_MIPS 2
#define AKSCOUNTER_ERROR 3
#define AKSCOUNTER_SIZE 4

/* Offsets for structure AKLhit */
#define AKLHIT_POCKET 0
#define AKLHIT_LAYER 1
#define AKLHIT_COUNTER 2
#define AKLHIT_MIPS 3
#define AKLHIT_TIME 4
#define AKLHIT_ONTFLAG 5
#define AKLHIT_SIZE 6

/* Offsets for structure DCHcluster */
#define DCHCLUSTER_VIEW 0
#define DCHCLUSTER_COORD 1
#define DCHCLUSTER_TIME 2
#define DCHCLUSTER_SIZE 3

/* Offsets for structure DCHhit */
#define DCHHIT_PLANE 0
#define DCHHIT_WIRE 1
#define DCHHIT_TIME 2
#define DCHHIT_DIST 3
#define DCHHIT_POS 4
#define DCHHIT_SIZE 5

/* Offsets for structure DCHspacepoint */
#define DCHSPACEPOINT_X 0
#define DCHSPACEPOINT_Y 1
#define DCHSPACEPOINT_Z 2
#define DCHSPACEPOINT_SIZE 3

/* Offsets for structure DCHtrack */
#define DCHTRACK_PQ 0
#define DCHTRACK_P 1
#define DCHTRACK_Q 2
#define DCHTRACK_PERR 3
#define DCHTRACK_CHI2 4
#define DCHTRACK_BX 5
#define DCHTRACK_BY 6
#define DCHTRACK_BDXDZ 7
#define DCHTRACK_BDYDZ 8
#define DCHTRACK_X 9
#define DCHTRACK_Y 10
#define DCHTRACK_DXDZ 11
#define DCHTRACK_DYDZ 12
#define DCHTRACK_TIME 13
#define DCHTRACK_QUALITY 14
#define DCHTRACK_SPNT 15
#define DCHTRACK_HODTIME 27
#define DCHTRACK_HODSTATUS 28
#define DCHTRACK_NHITS 29
#define DCHTRACK_NHIT 30
#define DCHTRACK_HIT 31
#define DCHTRACK_EXHAC 351
#define DCHTRACK_EYHAC 352
#define DCHTRACK_DDEADCELL 353
#define DCHTRACK_SIGXX 354
#define DCHTRACK_SIGYY 355
#define DCHTRACK_SIGDXDX 356
#define DCHTRACK_SIGDYDY 357
#define DCHTRACK_SIGXDX 358
#define DCHTRACK_SIGXY 359
#define DCHTRACK_SIGDXY 360
#define DCHTRACK_SIGXDY 361
#define DCHTRACK_SIGDXDY 362
#define DCHTRACK_SIGYDY 363
#define DCHTRACK_HITPATTERN 364
#define DCHTRACK_EFFICIENCY 365
#define DCHTRACK_SPAREINT 367
#define DCHTRACK_SPAREFLOAT 369
#define DCHTRACK_LKRCLU 371
#define DCHTRACK_EOVP 372
#define DCHTRACK_ESPY 373
#define DCHTRACK_MUVTIME 374
#define DCHTRACK_ANAVAR 375
#define DCHTRACK_ANAFLAG 395
#define DCHTRACK_SIZE 400

/* Offsets for structure DCHvertex */
#define DCHVERTEX_X 0
#define DCHVERTEX_Y 1
#define DCHVERTEX_Z 2
#define DCHVERTEX_CHI2 3
#define DCHVERTEX_BDXDZPOS 4
#define DCHVERTEX_BDYDZPOS 5
#define DCHVERTEX_BDXDZNEG 6
#define DCHVERTEX_BDYDZNEG 7
#define DCHVERTEX_NBDXDZTRACK 8
#define DCHVERTEX_BDXDZTRACK 9
#define DCHVERTEX_NBDYDZTRACK 16
#define DCHVERTEX_BDYDZTRACK 17
#define DCHVERTEX_CDA 24
#define DCHVERTEX_ERRORFLAG 25
#define DCHVERTEX_BLUEFLAG 26
#define DCHVERTEX_PPIPI 27
#define DCHVERTEX_MPIPI 28
#define DCHVERTEX_MLAMBDA 29
#define DCHVERTEX_MALAMBDA 30
#define DCHVERTEX_IPTRK 31
#define DCHVERTEX_INTRK 32
#define DCHVERTEX_NITRACK 33
#define DCHVERTEX_ITRACK 34
#define DCHVERTEX_RCOG 41
#define DCHVERTEX_PTSQKS 42
#define DCHVERTEX_PTSQKL 43
#define DCHVERTEX_PTPRIMEKS 44
#define DCHVERTEX_PTPRIMEKL 45
#define DCHVERTEX_DTINTKS 46
#define DCHVERTEX_DTINTKL 47
#define DCHVERTEX_DTOUTTKS 48
#define DCHVERTEX_DTOUTTKL 49
#define DCHVERTEX_DTINVKS 50
#define DCHVERTEX_DTINVKL 51
#define DCHVERTEX_DTOUTVKS 52
#define DCHVERTEX_DTOUTVKL 53
#define DCHVERTEX_EANGLE 54
#define DCHVERTEX_CTAU 55
#define DCHVERTEX_PHIDECAY 56
#define DCHVERTEX_ASP 57
#define DCHVERTEX_HODOTIMEANA 58
#define DCHVERTEX_TYPE 59
#define DCHVERTEX_CUTS 60
#define DCHVERTEX_IFLAG 61
#define DCHVERTEX_ANAVAR 62
#define DCHVERTEX_ANAFLAG 82
#define DCHVERTEX_SIZE 87

/* Offsets for structure DCHNROtdof */
#define DCHNROTDOF_TTIME 0
#define DCHNROTDOF_TSTATUS 1
#define DCHNROTDOF_SIZE 2

/* Offsets for structure DCHNROdof */
#define DCHNRODOF_DCHERROR 0
#define DCHNRODOF_NRO 1
#define DCHNRODOF_IPL 2
#define DCHNRODOF_RSTATUS 3
#define DCHNRODOF_NTDOF 4
#define DCHNRODOF_TDOF 5
#define DCHNRODOF_SIZE 95

/* Offsets for structure DCHNROhit */
#define DCHNROHIT_ID 0
#define DCHNROHIT_IPLANE 1
#define DCHNROHIT_IWIRE 2
#define DCHNROHIT_TIME 3
#define DCHNROHIT_ITRACK 4
#define DCHNROHIT_ITSLOT 5
#define DCHNROHIT_SIZE 6

/* Offsets for structure DCHNROgen */
#define DCHNROGEN_EVTIME 0
#define DCHNROGEN_TIMEST 1
#define DCHNROGEN_TRIGW 2
#define DCHNROGEN_FLAG 3
#define DCHNROGEN_NHIT 4
#define DCHNROGEN_HIT 5
#define DCHNROGEN_NDOF 10757
#define DCHNROGEN_DOF 10758
#define DCHNROGEN_SIZE 10853

/* Offsets for structure DCHFEstatus */
#define DCHFESTATUS_INTTRIG 0
#define DCHFESTATUS_F1PAR 1
#define DCHFESTATUS_PIPEFULL 2
#define DCHFESTATUS_PIPEFULLWIRE 3
#define DCHFESTATUS_SIZE 11

/* Offsets for structure DCHmult */
#define DCHMULT_MBXPLANEEFF 0
#define DCHMULT_L1TRK24EFF 6
#define DCHMULT_DCHSNOWERR 8
#define DCHMULT_MBXMULT 10
#define DCHMULT_TRK24ON 11
#define DCHMULT_SIZE 12

/* Offsets for structure SGNwire */
#define SGNWIRE_NUMBER 0
#define SGNWIRE_DRIFTTIME 1
#define SGNWIRE_SIZE 2

/* Offsets for structure SGNspacepoint */
#define SGNSPACEPOINT_X 0
#define SGNSPACEPOINT_Y 1
#define SGNSPACEPOINT_NWIRE 2
#define SGNSPACEPOINT_WIRE 3
#define SGNSPACEPOINT_QUALITY 19
#define SGNSPACEPOINT_SIZE 23

/* Offsets for structure SGNaccidental */
#define SGNACCIDENTAL_X 0
#define SGNACCIDENTAL_Y 1
#define SGNACCIDENTAL_TIME 2
#define SGNACCIDENTAL_SIZE 3

/* Offsets for structure SGNchamber */
#define SGNCHAMBER_NSPNT 0
#define SGNCHAMBER_SPNT 1
#define SGNCHAMBER_NACC 1151
#define SGNCHAMBER_ACC 1152
#define SGNCHAMBER_TOVRFLW 1302
#define SGNCHAMBER_ROVRFLW 1318
#define SGNCHAMBER_SIZE 1319

/* Offsets for structure SGNtrack */
#define SGNTRACK_P 0
#define SGNTRACK_CHI2 1
#define SGNTRACK_BX 2
#define SGNTRACK_BY 3
#define SGNTRACK_BDXDZ 4
#define SGNTRACK_BDYDZ 5
#define SGNTRACK_X 6
#define SGNTRACK_Y 7
#define SGNTRACK_DXDZ 8
#define SGNTRACK_DYDZ 9
#define SGNTRACK_SPNT 10
#define SGNTRACK_SIZE 14

/* Offsets for structure SGNvertex */
#define SGNVERTEX_X 0
#define SGNVERTEX_Y 1
#define SGNVERTEX_Z 2
#define SGNVERTEX_CDA 3
#define SGNVERTEX_FLAG 4
#define SGNVERTEX_SIZE 5

/* Offsets for structure HODhit */
#define HODHIT_PLANE 0
#define HODHIT_COUNTER 1
#define HODHIT_X 2
#define HODHIT_Y 3
#define HODHIT_PHEIGHT 4
#define HODHIT_TIME 5
#define HODHIT_UCTIME 6
#define HODHIT_PDSFLAG 7
#define HODHIT_SIZE 8

/* Offsets for structure HODneuthit */
#define HODNEUTHIT_PLANE 0
#define HODNEUTHIT_COUNTER 1
#define HODNEUTHIT_PULSE 2
#define HODNEUTHIT_TIME 3
#define HODNEUTHIT_SIZE 4

/* Offsets for structure LKRcluster */
#define LKRCLUSTER_ENERGY 0
#define LKRCLUSTER_EENERGY 1
#define LKRCLUSTER_E2SAMPALL 2
#define LKRCLUSTER_E77 3
#define LKRCLUSTER_X 4
#define LKRCLUSTER_Y 5
#define LKRCLUSTER_RMSX 6
#define LKRCLUSTER_RMSY 7
#define LKRCLUSTER_IMAX 8
#define LKRCLUSTER_TIME 9
#define LKRCLUSTER_ETIME 10
#define LKRCLUSTER_TLATCELL 11
#define LKRCLUSTER_DDEADCELL 12
#define LKRCLUSTER_UCENERGY 13
#define LKRCLUSTER_CELLSREAD 14
#define LKRCLUSTER_STATUS 15
#define LKRCLUSTER_SPACHACORR 16
#define LKRCLUSTER_ECORRKE3 17
#define LKRCLUSTER_SPAREINT1 18
#define LKRCLUSTER_SPAREFLOAT1 19
#define LKRCLUSTER_GAINMAX 20
#define LKRCLUSTER_ECELLMAX 21
#define LKRCLUSTER_TIMERAW 22
#define LKRCLUSTER_MCTAILCORR 23
#define LKRCLUSTER_ANAVAR 24
#define LKRCLUSTER_ANAFLAG 29
#define LKRCLUSTER_SIZE 34

/* Offsets for structure KABhit */
#define KABHIT_TLEAD 0
#define KABHIT_TTRAIL 1
#define KABHIT_TRACKID 2
#define KABHIT_SIZE 3

/* Offsets for structure KABstrip */
#define KABSTRIP_NHIT 0
#define KABSTRIP_HIT 1
#define KABSTRIP_SIZE 151

/* Offsets for structure KABdet */
#define KABDET_STRIP 0
#define KABDET_SIZE 7248

/* Offsets for structure KABtrack */
#define KABTRACK_PQ 0
#define KABTRACK_P 1
#define KABTRACK_Q 2
#define KABTRACK_UPORDOWN 3
#define KABTRACK_PERR 4
#define KABTRACK_CHI2 5
#define KABTRACK_X 6
#define KABTRACK_Y 7
#define KABTRACK_XUORD 8
#define KABTRACK_YUORD 9
#define KABTRACK_SIGXXUORD 10
#define KABTRACK_SIGYYUORD 11
#define KABTRACK_TIME 12
#define KABTRACK_TIMEUORD 13
#define KABTRACK_TIMEST2 14
#define KABTRACK_DXDZ 15
#define KABTRACK_DYDZ 16
#define KABTRACK_RECFLAG 17
#define KABTRACK_SIGXX 18
#define KABTRACK_SIGYY 19
#define KABTRACK_SIGTT 20
#define KABTRACK_SIGDXDX 21
#define KABTRACK_SIGDYDY 22
#define KABTRACK_SIGPY 23
#define KABTRACK_SIGXT 24
#define KABTRACK_SIGXDX 25
#define KABTRACK_SIGTDX 26
#define KABTRACK_SIGPX 27
#define KABTRACK_SIGXY 28
#define KABTRACK_SIGPT 29
#define KABTRACK_SIGYT 30
#define KABTRACK_SIGPDX 31
#define KABTRACK_SIGYDX 32
#define KABTRACK_SPAREINT 33
#define KABTRACK_SPAREFLOAT 35
#define KABTRACK_ANAVAR 37
#define KABTRACK_ANAFLAG 57
#define KABTRACK_SIZE 62

/* Offsets for structure KABFTWindow */
#define KABFTWINDOW_MAXPULSEHEIGHT 0
#define KABFTWINDOW_TFIRST 1
#define KABFTWINDOW_TMAX 2
#define KABFTWINDOW_NPULSEHEIGHT 3
#define KABFTWINDOW_PULSEHEIGHT 4
#define KABFTWINDOW_SIZE 304

/* Offsets for structure KABFChannel */
#define KABFCHANNEL_ID 0
#define KABFCHANNEL_MODE 1
#define KABFCHANNEL_DECFLAG 2
#define KABFCHANNEL_NTWINDOW 3
#define KABFCHANNEL_TWINDOW 4
#define KABFCHANNEL_SIZE 18244

/* Offsets for structure KABFADC */
#define KABFADC_TIMESTAMP 0
#define KABFADC_OFFSET 1
#define KABFADC_NCHANNEL 2
#define KABFADC_CHANNEL 3
#define KABFADC_SIZE 364883

/* Offsets for structure NHOhit */
#define NHOHIT_COUNTER 0
#define NHOHIT_X 1
#define NHOHIT_Y 2
#define NHOHIT_PHEIGHT 3
#define NHOHIT_TIME 4
#define NHOHIT_UCTIME 5
#define NHOHIT_PDSFLAG 6
#define NHOHIT_SIZE 7

/* Offsets for structure HACcluster */
#define HACCLUSTER_ENERGY 0
#define HACCLUSTER_BFRATIO 1
#define HACCLUSTER_X 2
#define HACCLUSTER_Y 3
#define HACCLUSTER_RMSX 4
#define HACCLUSTER_RMSY 5
#define HACCLUSTER_EMAXX 6
#define HACCLUSTER_EMAXY 7
#define HACCLUSTER_TIME 8
#define HACCLUSTER_RECFLAG 9
#define HACCLUSTER_SIZE 10

/* Offsets for structure HACcell */
#define HACCELL_IDCELL 0
#define HACCELL_ENERGY 1
#define HACCELL_SIZE 2

/* Offsets for structure MUVhit */
#define MUVHIT_X 0
#define MUVHIT_Y 1
#define MUVHIT_TIME 2
#define MUVHIT_DTIME 3
#define MUVHIT_STATUS 4
#define MUVHIT_PLANE 5
#define MUVHIT_CHI2 7
#define MUVHIT_TRACKID 8
#define MUVHIT_VERTEXID 9
#define MUVHIT_SIZE 10

/* Offsets for structure PMUVhit */
#define PMUVHIT_TIME 0
#define PMUVHIT_WIDTH 1
#define PMUVHIT_INFO 2
#define PMUVHIT_SIZE 3

/* Offsets for structure PMUVchannel */
#define PMUVCHANNEL_N 0
#define PMUVCHANNEL_NHIT 1
#define PMUVCHANNEL_HIT 2
#define PMUVCHANNEL_SIZE 62

/* Offsets for structure L3filter */
#define L3FILTER_INDEX 0
#define L3FILTER_INFO 1
#define L3FILTER_SIZE 2

/* Offsets for structure L3particle */
#define L3PARTICLE_TYPE 0
#define L3PARTICLE_SIZE 1

/* Offsets for structure etaCluster */
#define ETACLUSTER_FLAG 0
#define ETACLUSTER_NCELL 1
#define ETACLUSTER_IMAX 2
#define ETACLUSTER_NREC 3
#define ETACLUSTER_ECELL 4
#define ETACLUSTER_SIZE 29

/* Offsets for structure etaSummary */
#define ETASUMMARY_FLAG 0
#define ETASUMMARY_XVTXZ 1
#define ETASUMMARY_XCOG 2
#define ETASUMMARY_EMESON 3
#define ETASUMMARY_NCLU 4
#define ETASUMMARY_CLU 5
#define ETASUMMARY_SIZE 1455

/* Offsets for structure ananeut */
#define ANANEUT_ESC 0
#define ANANEUT_IFLAG 1
#define ANANEUT_CEM 2
#define ANANEUT_INC 5
#define ANANEUT_RELLI 11
#define ANANEUT_CTAU 12
#define ANANEUT_EKAON 13
#define ANANEUT_LKRTIME 14
#define ANANEUT_LKRNHODTIME 15
#define ANANEUT_NTUSED 16
#define ANANEUT_NHODTIME 17
#define ANANEUT_CUTS 18
#define ANANEUT_SIZE 19

/* Offsets for structure anacharg */
#define ANACHARG_KTYPE 0
#define ANACHARG_IFLAG 1
#define ANACHARG_IVERTEX 2
#define ANACHARG_CUTS 3
#define ANACHARG_SIZE 4

/* Offsets for structure anachodcount */
#define ANACHODCOUNT_PLANE 0
#define ANACHODCOUNT_COUNTER 1
#define ANACHODCOUNT_TIME 2
#define ANACHODCOUNT_SIG 3
#define ANACHODCOUNT_SIZE 4

/* Offsets for structure anacharghod */
#define ANACHARGHOD_HODOTIME 0
#define ANACHARGHOD_ITRACE 1
#define ANACHARGHOD_NACOUNT 3
#define ANACHARGHOD_ACOUNT 4
#define ANACHARGHOD_HSIGG 84
#define ANACHARGHOD_VSIGG 85
#define ANACHARGHOD_SIZE 86

/* Offsets for structure anaprothit */
#define ANAPROTHIT_INDEXHIT 0
#define ANAPROTHIT_SIZE 2

/* Offsets for structure anaproton */
#define ANAPROTON_PROTTIME 0
#define ANAPROTON_PROTSTAT 1
#define ANAPROTON_NPROTHIT 2
#define ANAPROTON_PROTHIT 3
#define ANAPROTON_SIZE 43

/* Offsets for structure anatagger */
#define ANATAGGER_NAPROT 0
#define ANATAGGER_APROT 1
#define ANATAGGER_NPROTLADDER 4301
#define ANATAGGER_NPROTMONITOR 4302
#define ANATAGGER_SIZE 4303

/* Offsets for structure anaaks */
#define ANAAKS_FLAG 0
#define ANAAKS_SIZE 1

/* Offsets for structure anacalled */
#define ANACALLED_SELCHARGED 0
#define ANACALLED_SEL2PI0 1
#define ANACALLED_SEL3PI0 2
#define ANACALLED_BLUEFIELD 3
#define ANACALLED_LKRPEDCOR 4
#define ANACALLED_LKRPOSCOR 5
#define ANACALLED_LKRSHARING 6
#define ANACALLED_HODOTIME 7
#define ANACALLED_NHODTIME 8
#define ANACALLED_LKRTIME 9
#define ANACALLED_TAGTIME 10
#define ANACALLED_AKSFLAG 11
#define ANACALLED_MUON_REC 12
#define ANACALLED_MUON_REJECT 13
#define ANACALLED_GEOMCOR 14
#define ANACALLED_MAGNETCOR 15
#define ANACALLED_NEWCHARGED 16
#define ANACALLED_MUON_TRACKREC 17
#define ANACALLED_MUON_VTXREC 18
#define ANACALLED_LKRCALCOR 19
#define ANACALLED_LKRCALCOR1 20
#define ANACALLED_LKRCALCOR2 21
#define ANACALLED_LKRCALCOR3 22
#define ANACALLED_LKRCALHI2K 23
#define ANACALLED_SEL2GAM 24
#define ANACALLED_SEL3PIC 25
#define ANACALLED_SEL3PIN 26
#define ANACALLED_SIZE 27

/* Offsets for structure cmpEvent */
#define CMPEVENT_N 1
#define CMPEVENT_TRIGWORD 2
#define CMPEVENT_TIMESTAMP 3
#define CMPEVENT_RECFLAG 4
#define CMPEVENT_FLAGCORR 5
#define CMPEVENT_EVTFSPARE 6
#define CMPEVENT_EVTISPARE 16
#define CMPEVENT_DBERR 26
#define CMPEVENT_RNDM 27
#define CMPEVENT_NTSTAMP 109
#define CMPEVENT_TSTAMP 110
#define CMPEVENT_KLMON 132
#define CMPEVENT_KLMON3US 134
#define CMPEVENT_QXMON 136
#define CMPEVENT_QXMON3US 138
#define CMPEVENT_KSMON 140
#define CMPEVENT_AKSMON 142
#define CMPEVENT_MAINSPHASE 144
#define CMPEVENT_SPSPHASE 145
#define CMPEVENT_MAINSPHASERAW 146
#define CMPEVENT_SPSPHASERAW 147
#define CMPEVENT_FEMAINSPHASE 148
#define CMPEVENT_FESPSPHASE 149
#define CMPEVENT_NTRIG 150
#define CMPEVENT_TRIG 151
#define CMPEVENT_PATERRFLAG 407
#define CMPEVENT_PATSTATUS 408
#define CMPEVENT_TAGANTIC 409
#define CMPEVENT_NTAG 410
#define CMPEVENT_TAG 411
#define CMPEVENT_TAGERRFLAG 4131
#define CMPEVENT_TAGSTATUS 4132
#define CMPEVENT_NKSM 4133
#define CMPEVENT_KSM 4134
#define CMPEVENT_KSMERRFLAG 4214
#define CMPEVENT_KSMSTATUS 4215
#define CMPEVENT_BEAMINTKS 4216
#define CMPEVENT_BEAMINTKL 4228
#define CMPEVENT_AKLTIME 4240
#define CMPEVENT_NAKL 4241
#define CMPEVENT_AKL 4242
#define CMPEVENT_AKLERRFLAG 4842
#define CMPEVENT_AKLSTATUS 4843
#define CMPEVENT_AKSMIPS 4844
#define CMPEVENT_AKSTIME 4849
#define CMPEVENT_AKS 4854
#define CMPEVENT_AKSERRFLAG 4882
#define CMPEVENT_AKSSTATUS 4883
#define CMPEVENT_DCHBZ 4884
#define CMPEVENT_DCHZ 4885
#define CMPEVENT_DCHBZCORR 4886
#define CMPEVENT_DCHZCORR 4887
#define CMPEVENT_DCHNHITS 4888
#define CMPEVENT_DCHOVRFLOW 4904
#define CMPEVENT_BESTVERTEX 4905
#define CMPEVENT_NDCHCLU 4906
#define CMPEVENT_DCHCLU 4907
#define CMPEVENT_NTRACK 5207
#define CMPEVENT_TRACK 5208
#define CMPEVENT_NTRACKCORR 21208
#define CMPEVENT_TRACKCORR 21209
#define CMPEVENT_VTXFRRDVX 37209
#define CMPEVENT_NVERTEX 37210
#define CMPEVENT_VERTEX 37211
#define CMPEVENT_NVERTEXCORR 45911
#define CMPEVENT_VERTEXCORR 45912
#define CMPEVENT_DCHERRFLAG 54612
#define CMPEVENT_DCHERRFLAGPDS 54613
#define CMPEVENT_DCHSTATUS 54614
#define CMPEVENT_MBOXDEADTIME 54615
#define CMPEVENT_DCHNRO 54616
#define CMPEVENT_DCHFE 65469
#define CMPEVENT_DCHEFFMULT 65480
#define CMPEVENT_SGNTIME 65492
#define CMPEVENT_CHAMBER 65493
#define CMPEVENT_NSGNTRK 70769
#define CMPEVENT_SGNTRK 70770
#define CMPEVENT_NSGNVTX 71330
#define CMPEVENT_SGNVTX 71331
#define CMPEVENT_HODTIME 71831
#define CMPEVENT_NHOD 71832
#define CMPEVENT_HOD 71833
#define CMPEVENT_HODNEUTFLAG 72233
#define CMPEVENT_NHODNEUT 72234
#define CMPEVENT_HODNEUT 72235
#define CMPEVENT_HODERRFLAG 72299
#define CMPEVENT_HODSTATUS 72300
#define CMPEVENT_LKRETOTCELL 72301
#define CMPEVENT_LKRENERGY 72302
#define CMPEVENT_NLKR 72303
#define CMPEVENT_LKR 72304
#define CMPEVENT_LKRERRFLAG 74004
#define CMPEVENT_LKRSTATUS 74005
#define CMPEVENT_LKRDOWNSCALED 74006
#define CMPEVENT_NKABHIT 74007
#define CMPEVENT_KAB 74008
#define CMPEVENT_NKABTRK 117496
#define CMPEVENT_KABTRK 117497
#define CMPEVENT_KABERRFLAG 120597
#define CMPEVENT_KABERRFLAGPDS 120598
#define CMPEVENT_NKABFADC 120599
#define CMPEVENT_KABFADC 120600
#define CMPEVENT_NUTHITMAP 485483
#define CMPEVENT_NUTXPEAK 485487
#define CMPEVENT_NUTYPEAK 485491
#define CMPEVENT_NUTNXPEAK 485495
#define CMPEVENT_NUTNYPEAK 485499
#define CMPEVENT_NUTM0 485503
#define CMPEVENT_NUTM1 485505
#define CMPEVENT_NUTM2 485507
#define CMPEVENT_NUTM0SMP 485509
#define CMPEVENT_NUTM1SMP 485515
#define CMPEVENT_NUTM2SMP 485516
#define CMPEVENT_NUTHACSMP 485517
#define CMPEVENT_NUTHACESUM 485518
#define CMPEVENT_NUTTS 485524
#define CMPEVENT_SPY_X 485525
#define CMPEVENT_SPY_Y 485589
#define CMPEVENT_NUTERRFLAG 485653
#define CMPEVENT_NUTSTATUS 485654
#define CMPEVENT_NHOTIME 485655
#define CMPEVENT_NNHO 485656
#define CMPEVENT_NHO 485657
#define CMPEVENT_NHOERRFLAG 486007
#define CMPEVENT_NHOSTATUS 486008
#define CMPEVENT_HACENERGY 486009
#define CMPEVENT_NGOODHAC 486010
#define CMPEVENT_NHAC 486011
#define CMPEVENT_HAC 486012
#define CMPEVENT_HACERRFLAG 486512
#define CMPEVENT_HACSTATUS 486513
#define CMPEVENT_NPHAC 486514
#define CMPEVENT_PHAC 486515
#define CMPEVENT_NMUV 486867
#define CMPEVENT_MUV 486868
#define CMPEVENT_NPMUV 487368
#define CMPEVENT_PMUV 487369
#define CMPEVENT_NPMUVNEW 490841
#define CMPEVENT_PMUVNEW 490842
#define CMPEVENT_MUVERRFLAG 494314
#define CMPEVENT_MUVSTATUS 494315
#define CMPEVENT_L3EVTYPE 494316
#define CMPEVENT_L3STATUS 494317
#define CMPEVENT_L3ERRDEC 494318
#define CMPEVENT_L3ERRREC 494319
#define CMPEVENT_L3RTRSTATUS 494320
#define CMPEVENT_L3TRIGWORD 494321
#define CMPEVENT_L3ONLINETRIGWORD 494323
#define CMPEVENT_L3BTRIGWORD 494325
#define CMPEVENT_L3ACTIONDOWNSCALE 494327
#define CMPEVENT_L3ACTIONDOWNSCALE2 494328
#define CMPEVENT_L3FILTERDOWNSCALE 494329
#define CMPEVENT_L3ACTIONOVL 494330
#define CMPEVENT_L3ACTIONOVL2 494331
#define CMPEVENT_L3FILTEROVL 494332
#define CMPEVENT_L3CUTFLAG 494333
#define CMPEVENT_L3CUTFLAG2 494334
#define CMPEVENT_L3RAREDECAY 494344
#define CMPEVENT_L3EVSTEER 494345
#define CMPEVENT_NFILTER 494346
#define CMPEVENT_FILTER 494347
#define CMPEVENT_NPART 494379
#define CMPEVENT_PART 494380
#define CMPEVENT_NTRHIST 494390
#define CMPEVENT_TRHIST 494391
#define CMPEVENT_L3NCELLS 494411
#define CMPEVENT_L3NCELLABT 494412
#define CMPEVENT_L3RAWENERGY 494413
#define CMPEVENT_L3DCHHITS 494414
#define CMPEVENT_L3EP 494418
#define CMPEVENT_L3MINDIST 494419
#define CMPEVENT_L3ZVERT 494420
#define CMPEVENT_L3CDA 494421
#define CMPEVENT_L3PIPIMASS 494422
#define CMPEVENT_L3PPAIR 494423
#define CMPEVENT_L3COGC 494424
#define CMPEVENT_L3TAU 494425
#define CMPEVENT_L3NCLUS 494426
#define CMPEVENT_L3PI0PI0MASS 494427
#define CMPEVENT_L3COGN 494429
#define CMPEVENT_L2BSTATUS 494430
#define CMPEVENT_L2BCOMCLUST 494431
#define CMPEVENT_L2BSHADR 494432
#define CMPEVENT_L2BSHX 494438
#define CMPEVENT_L2BSHY 494444
#define CMPEVENT_L2BSHENERGY 494450
#define CMPEVENT_L2BSHTIME 494456
#define CMPEVENT_L2BSHXRMS 494462
#define CMPEVENT_L2BSHYRMS 494468
#define CMPEVENT_L3SPARE 494474
#define CMPEVENT_L3SHOWERWIDTH 494476
#define CMPEVENT_STATUS 494477
#define CMPEVENT_CMPFILTER 494478
#define CMPEVENT_NOVRFLWSIM 494479
#define CMPEVENT_OVRFLWSIMBEF 494480
#define CMPEVENT_OVRFLWSIMAFT 494481
#define CMPEVENT_NTRIGWORDL 494482
#define CMPEVENT_TRIGWORDL 494483
#define CMPEVENT_NTIMESTAMPL 564483
#define CMPEVENT_TIMESTAMPL 564484
#define CMPEVENT_NDCHDECERRORL 634484
#define CMPEVENT_DCHDECERRORL 634485
#define CMPEVENT_NLKRHACDECERRORL 704485
#define CMPEVENT_LKRHACDECERRORL 704486
#define CMPEVENT_NCHARGEDINFOL 774486
#define CMPEVENT_CHARGEDINFOL 774487
#define CMPEVENT_NNEUTRALINFOL 844487
#define CMPEVENT_NEUTRALINFOL 844488
#define CMPEVENT_NETASUMM 914488
#define CMPEVENT_ETASUMM 914489
#define CMPEVENT_NTHMPACKEDDATA 915944
#define CMPEVENT_THMPACKEDDATA 915945
#define CMPEVENT_SPAREINT 916035
#define CMPEVENT_SPARE01INT 916045
#define CMPEVENT_SPAREFLOAT 916055
#define CMPEVENT_SPARE01FLOAT 916065
#define CMPEVENT_NTRIGBEF 916075
#define CMPEVENT_TIMETOPREV 916076
#define CMPEVENT_ANEUT 916077
#define CMPEVENT_ACHARG 916096
#define CMPEVENT_ACHOD 916100
#define CMPEVENT_ATAG 916186
#define CMPEVENT_AAKS 920489
#define CMPEVENT_ACALL 920490
#define CMPEVENT_SIZE 920517

/* Offsets for structure XoffDet */
#define XOFFDET_DATA 0
#define XOFFDET_NTRANSITION 3
#define XOFFDET_FRACTIMEON 4
#define XOFFDET_FIRSTTIMEON 5
#define XOFFDET_SIZE 6

/* Offsets for structure NSstat */
#define NSSTAT_BEND 0
#define NSSTAT_QUAD 1
#define NSSTAT_TRIM 2
#define NSSTAT_SCRAPER 3
#define NSSTAT_COLL 4
#define NSSTAT_COLR 5
#define NSSTAT_SIZE 6

/* Offsets for structure BeamNonStandard */
#define BEAMNONSTANDARD_P42 0
#define BEAMNONSTANDARD_K12 6
#define BEAMNONSTANDARD_TARGT4 12
#define BEAMNONSTANDARD_TARGT10 13
#define BEAMNONSTANDARD_TARGKSY 14
#define BEAMNONSTANDARD_TARGKSX 15
#define BEAMNONSTANDARD_TAXMOT7 16
#define BEAMNONSTANDARD_TAXMOT8 17
#define BEAMNONSTANDARD_TAXMOT17 18
#define BEAMNONSTANDARD_TAXMOT18 19
#define BEAMNONSTANDARD_T10COLLSTART 20
#define BEAMNONSTANDARD_T10COLLEND 21
#define BEAMNONSTANDARD_COLLPROTTAG 22
#define BEAMNONSTANDARD_COLLPROTTAGX 23
#define BEAMNONSTANDARD_COLLPROTTAGY 24
#define BEAMNONSTANDARD_COLLCLEANCOLL 25
#define BEAMNONSTANDARD_COLLCLEANCOLLX 26
#define BEAMNONSTANDARD_COLLCLEANCOLLY 27
#define BEAMNONSTANDARD_COLLDEFCOLL 28
#define BEAMNONSTANDARD_COLLDEFCOLLX 29
#define BEAMNONSTANDARD_COLLDEFCOLLY 30
#define BEAMNONSTANDARD_CRYDISHOR 31
#define BEAMNONSTANDARD_CRYDISVER 32
#define BEAMNONSTANDARD_CRYROTHOR 33
#define BEAMNONSTANDARD_CRYROTVER 34
#define BEAMNONSTANDARD_CRYTEMP 35
#define BEAMNONSTANDARD_XAKSDISTHOR 36
#define BEAMNONSTANDARD_XAKSROTHOR 37
#define BEAMNONSTANDARD_XAKSROTVER 38
#define BEAMNONSTANDARD_P42CONV 39
#define BEAMNONSTANDARD_K12CONV 40
#define BEAMNONSTANDARD_VACCPUMP55 41
#define BEAMNONSTANDARD_VACCPUMP56 42
#define BEAMNONSTANDARD_VACCPUMP98 43
#define BEAMNONSTANDARD_VACCPUMP58 44
#define BEAMNONSTANDARD_VACCVALVE56 45
#define BEAMNONSTANDARD_VACCVALVE58 46
#define BEAMNONSTANDARD_SPSBEND1K12 47
#define BEAMNONSTANDARD_SPSBEND2K12 48
#define BEAMNONSTANDARD_SPSBEND3K12 49
#define BEAMNONSTANDARD_SPSBEND4K12 50
#define BEAMNONSTANDARD_SPSBEND5K12 51
#define BEAMNONSTANDARD_P42FILENUMBER 52
#define BEAMNONSTANDARD_K12FILENUMBER 53
#define BEAMNONSTANDARD_SIZE 54

/* Offsets for structure BeamStandard */
#define BEAMSTANDARD_SPSDATE 0
#define BEAMSTANDARD_SPSHOUR 1
#define BEAMSTANDARD_SPST4INT 2
#define BEAMSTANDARD_SPST4SYM 3
#define BEAMSTANDARD_SPST10INT 4
#define BEAMSTANDARD_SPST4 5
#define BEAMSTANDARD_SPSK12 6
#define BEAMSTANDARD_SPSP0 7
#define BEAMSTANDARD_SPSMNP33COIL1 8
#define BEAMSTANDARD_SPSMNP33COIL2 9
#define BEAMSTANDARD_SPSBEND1K12 10
#define BEAMSTANDARD_SPSSTATUS 11
#define BEAMSTANDARD_SPARE 12
#define BEAMSTANDARD_SIZE 16

/* Offsets for structure TSscalars97 */
#define TSSCALARS97_Q2X1MUXNAKL 0
#define TSSCALARS97_Q2XN1MUXNAKL 1
#define TSSCALARS97_QXXN1MUXNAKL 2
#define TSSCALARS97_QXXN1MU 3
#define TSSCALARS97_QXOVER2 4
#define TSSCALARS97_QX 5
#define TSSCALARS97_QXFINETIME0 6
#define TSSCALARS97_QXFINETIME1 7
#define TSSCALARS97_QXFT0MB 8
#define TSSCALARS97_QXFT1MB 9
#define TSSCALARS97_MBOXDEBREQ 10
#define TSSCALARS97_L1COD1MB 11
#define TSSCALARS97_L1COD2MB 12
#define TSSCALARS97_L1COD3MB 13
#define TSSCALARS97_L1STRBXL1ON 14
#define TSSCALARS97_L1STRBMB 15
#define TSSCALARS97_ONETRACKDC1 16
#define TSSCALARS97_TWOTHREETRACKDC1 17
#define TSSCALARS97_FOURTRACKSDC1 18
#define TSSCALARS97_OVFLOWDC1 19
#define TSSCALARS97_TOTORAKL 20
#define TSSCALARS97_QXOVER128 21
#define TSSCALARS97_Q2X2MUXNAKL 22
#define TSSCALARS97_T0NXN1MUXNAKL 23
#define TSSCALARS97_TRIGNOXOFF 24
#define TSSCALARS97_TRIGNOXWRIT 25
#define TSSCALARS97_LASER 26
#define TSSCALARS97_LKRCALNZS 27
#define TSSCALARS97_LKRCALZS 28
#define TSSCALARS97_HACPULSER 29
#define TSSCALARS97_PMBPULSER 30
#define TSSCALARS97_RANDOMKL 31
#define TSSCALARS97_RANDOMKS 32
#define TSSCALARS97_S2HVSPARK 33
#define TSSCALARS97_FULLTSLOST 34
#define TSSCALARS97_XOFFTSLOST 35
#define TSSCALARS97_L1LASER 36
#define TSSCALARS97_L1LKRCALNZS 37
#define TSSCALARS97_L1LKRCALZS 38
#define TSSCALARS97_L1HACPULS 39
#define TSSCALARS97_L1PMBPULS 40
#define TSSCALARS97_L1RANDKL 41
#define TSSCALARS97_L1RANDKS 42
#define TSSCALARS97_L1L1ONTRANS 43
#define TSSCALARS97_L1Q2X1MUXNAKL 44
#define TSSCALARS97_L1Q2XN1MUXNAKL 45
#define TSSCALARS97_L1QXXN1MUXNAKL 46
#define TSSCALARS97_L1QXXN1MU 47
#define TSSCALARS97_L1QXOVER2 48
#define TSSCALARS97_L1QX 49
#define TSSCALARS97_L1QXFINETIME0 50
#define TSSCALARS97_L1QXFINETIME1 51
#define TSSCALARS97_L1OVFLOWDC1 52
#define TSSCALARS97_L1ONETRACKDC1 53
#define TSSCALARS97_L1TWOTHREETRACKDC1 54
#define TSSCALARS97_L1FOURTRACKSDC1 55
#define TSSCALARS97_L1TONXN1MUXNA 56
#define TSSCALARS97_L1Q2X2MUXNAK 57
#define TSSCALARS97_L1QXOVER128 58
#define TSSCALARS97_L1AKL 59
#define TSSCALARS97_NT2PI0 60
#define TSSCALARS97_NTLKRMBIAS 61
#define TSSCALARS97_NT2PI0NOPK 62
#define TSSCALARS97_NTETOT 63
#define TSSCALARS97_NTACCID 64
#define TSSCALARS97_NTMUMUGAM 65
#define TSSCALARS97_NTMUMUEE 66
#define TSSCALARS97_NTDALITZ 67
#define TSSCALARS97_NTSUSY2G 68
#define TSSCALARS97_NTFINETIME0 69
#define TSSCALARS97_NTFINETIME1 70
#define TSSCALARS97_NTTIMEPEAK 71
#define TSSCALARS97_NTSUSY3P 72
#define TSSCALARS97_CPDPATTERN 73
#define TSSCALARS97_Q1XN1MU 74
#define TSSCALARS97_Q2 75
#define TSSCALARS97_QOR 76
#define TSSCALARS97_ONEMU 77
#define TSSCALARS97_T0NXN1MU 78
#define TSSCALARS97_Q1X1MU 79
#define TSSCALARS97_MBOVFLOW12 80
#define TSSCALARS97_MBOVFLOW4 81
#define TSSCALARS97_MBTOOCPLX 82
#define TSSCALARS97_MBINTIME 83
#define TSSCALARS97_MBZOKRARE 84
#define TSSCALARS97_MBPIPLUSPIMINUSPI0 85
#define TSSCALARS97_MBPIPLUSPIMINUSOK 86
#define TSSCALARS97_MBFATAL 87
#define TSSCALARS97_MBFORCEREAD 88
#define TSSCALARS97_MBZOK 89
#define TSSCALARS97_MBMASSOK 90
#define TSSCALARS97_MBSTRBTOTS 91
#define TSSCALARS97_NTETOTBIAS 92
#define TSSCALARS97_SIZE 93

/* Offsets for structure TSscalars */
#define TSSCALARS_NSCALER 0
#define TSSCALARS_SCALER 1
#define TSSCALARS_SIZE 101

/* Offsets for structure L2TSscalars97 */
#define L2TSSCALARS97_PIPLUSPIMINUS 0
#define L2TSSCALARS97_L1PIPLUSPIMINUS 1
#define L2TSSCALARS97_L1PPWDOG 2
#define L2TSSCALARS97_QOR 3
#define L2TSSCALARS97_PI0PI0 4
#define L2TSSCALARS97_NHOD 5
#define L2TSSCALARS97_LKRMBIAS 6
#define L2TSSCALARS97_EPSMBIAS 7
#define L2TSSCALARS97_PIPLUSPIMINUSPI0 8
#define L2TSSCALARS97_MUMUG 9
#define L2TSSCALARS97_DALITZ 10
#define L2TSSCALARS97_SUSY 11
#define L2TSSCALARS97_RANKLKS 12
#define L2TSSCALARS97_L1ONCNT 13
#define L2TSSCALARS97_XLOSTTR 14
#define L2TSSCALARS97_FLOSTTR 15
#define L2TSSCALARS97_TWOPI0NOPK 16
#define L2TSSCALARS97_SIZE 17

/* Offsets for structure L2TSscalars */
#define L2TSSCALARS_NSCALER 0
#define L2TSSCALARS_SCALER 1
#define L2TSSCALARS_SIZE 21

/* Offsets for structure AKLscalars */
#define AKLSCALARS_AKL1OR 0
#define AKLSCALARS_AKL2OR 1
#define AKLSCALARS_AKL3OR 2
#define AKLSCALARS_AKL4OR 3
#define AKLSCALARS_AKL5OR 4
#define AKLSCALARS_AKL6OR 5
#define AKLSCALARS_AKL7OR 6
#define AKLSCALARS_AKLOR 7
#define AKLSCALARS_AKL1ORAND 8
#define AKLSCALARS_AKL2ORAND 9
#define AKLSCALARS_AKL3ORAND 10
#define AKLSCALARS_AKL4ORAND 11
#define AKLSCALARS_AKL5ORAND 12
#define AKLSCALARS_AKL6ORAND 13
#define AKLSCALARS_AKL7ORAND 14
#define AKLSCALARS_AKLORAND 15
#define AKLSCALARS_SIZE 16

/* Offsets for structure TriggerSupervisor */
#define TRIGGERSUPERVISOR_TSSCAL97 0
#define TRIGGERSUPERVISOR_TSSCAL 93
#define TRIGGERSUPERVISOR_L2TSSCAL97 194
#define TRIGGERSUPERVISOR_L2TSSCAL 211
#define TRIGGERSUPERVISOR_AKLSCAL 232
#define TRIGGERSUPERVISOR_SIZE 248

/* Offsets for structure BeamMonitor */
#define BEAMMONITOR_BADMAC 0
#define BEAMMONITOR_FASTSPILLKS 1
#define BEAMMONITOR_AVERAGEAKS 2
#define BEAMMONITOR_MAXAKS 3
#define BEAMMONITOR_RMSAKS 4
#define BEAMMONITOR_SLOWDCKS 5
#define BEAMMONITOR_EXTRLENKS 6
#define BEAMMONITOR_FASTSPILLKL 7
#define BEAMMONITOR_AVERAGEBCTR 8
#define BEAMMONITOR_MAXBCTR 9
#define BEAMMONITOR_RMSBCTR 10
#define BEAMMONITOR_SLOWDCKL 11
#define BEAMMONITOR_EXTRLENKL 12
#define BEAMMONITOR_SPARE 13
#define BEAMMONITOR_NSAMPLE 16
#define BEAMMONITOR_FCLOCK 17
#define BEAMMONITOR_FHAC1 18
#define BEAMMONITOR_FHAC2 19
#define BEAMMONITOR_FMUONS 20
#define BEAMMONITOR_FAKS 21
#define BEAMMONITOR_FT1T2 22
#define BEAMMONITOR_FQX 23
#define BEAMMONITOR_FBCTR 24
#define BEAMMONITOR_FTWOMU 25
#define BEAMMONITOR_FHV1 26
#define BEAMMONITOR_FHVD1 27
#define BEAMMONITOR_FHVD2 28
#define BEAMMONITOR_FHVD3 29
#define BEAMMONITOR_FHVD4 30
#define BEAMMONITOR_FDELCO 31
#define BEAMMONITOR_FAKL 32
#define BEAMMONITOR_FKSMDELCO 33
#define BEAMMONITOR_FKSM 34
#define BEAMMONITOR_CLOCK 35
#define BEAMMONITOR_AKS 435
#define BEAMMONITOR_T1T2 835
#define BEAMMONITOR_QX 1235
#define BEAMMONITOR_BCTR 1635
#define BEAMMONITOR_DELCO 2035
#define BEAMMONITOR_KSMDELCO 2435
#define BEAMMONITOR_KSM 2835
#define BEAMMONITOR_SIZE 3235

/* Offsets for structure BeamMonitor01 */
#define BEAMMONITOR01_BADMAC 0
#define BEAMMONITOR01_FASTSPILLKS 1
#define BEAMMONITOR01_AVERAGEAKS 2
#define BEAMMONITOR01_MAXAKS 3
#define BEAMMONITOR01_RMSAKS 4
#define BEAMMONITOR01_SLOWDCKS 5
#define BEAMMONITOR01_EXTRLENKS 6
#define BEAMMONITOR01_FASTSPILLKL 7
#define BEAMMONITOR01_AVERAGEBCTR 8
#define BEAMMONITOR01_MAXBCTR 9
#define BEAMMONITOR01_RMSBCTR 10
#define BEAMMONITOR01_SLOWDCKL 11
#define BEAMMONITOR01_EXTRLENKL 12
#define BEAMMONITOR01_SPARE 13
#define BEAMMONITOR01_NSAMPLE 16
#define BEAMMONITOR01_FCLOCK 17
#define BEAMMONITOR01_FHAC1 18
#define BEAMMONITOR01_FHAC2 19
#define BEAMMONITOR01_FMUONS 20
#define BEAMMONITOR01_FAKS 21
#define BEAMMONITOR01_FT1T2 22
#define BEAMMONITOR01_FQX 23
#define BEAMMONITOR01_FBCTR 24
#define BEAMMONITOR01_FTWOMU 25
#define BEAMMONITOR01_FHV1 26
#define BEAMMONITOR01_FHVD1 27
#define BEAMMONITOR01_FHVD2 28
#define BEAMMONITOR01_FHVD3 29
#define BEAMMONITOR01_FHVD4 30
#define BEAMMONITOR01_FDELCO 31
#define BEAMMONITOR01_FAKL 32
#define BEAMMONITOR01_FKSMDELCO 33
#define BEAMMONITOR01_FKSM 34
#define BEAMMONITOR01_CLOCK 35
#define BEAMMONITOR01_AKS 835
#define BEAMMONITOR01_T1T2 1635
#define BEAMMONITOR01_QX 2435
#define BEAMMONITOR01_BCTR 3235
#define BEAMMONITOR01_DELCO 4035
#define BEAMMONITOR01_KSMDELCO 4835
#define BEAMMONITOR01_KSM 5635
#define BEAMMONITOR01_SIZE 6435

/* Offsets for structure LkrCalib */
#define LKRCALIB_TRIGGER 0
#define LKRCALIB_DAC 30
#define LKRCALIB_SIZE 31

/* Offsets for structure DataMerger */
#define DATAMERGER_ERROR 0
#define DATAMERGER_DETERROR 1
#define DATAMERGER_SIZE 2

/* Offsets for structure TagClock */
#define TAGCLOCK_PHASE 0
#define TAGCLOCK_REFVOLT1 1
#define TAGCLOCK_REFVOLT2 2
#define TAGCLOCK_SIZE 3

/* Offsets for structure MUVScalars */
#define MUVSCALARS_MUONS 0
#define MUVSCALARS_TWOMUONS 1
#define MUVSCALARS_SIZE 2

/* Offsets for structure BadBurst */
#define BADBURST_CALL 0
#define BADBURST_SKIP 1
#define BADBURST_LKR 2
#define BADBURST_DCH 3
#define BADBURST_NUT 4
#define BADBURST_MBX 5
#define BADBURST_HAC 6
#define BADBURST_TAG 7
#define BADBURST_MUV 8
#define BADBURST_HODC 9
#define BADBURST_HODN 10
#define BADBURST_PMB 11
#define BADBURST_AKS 12
#define BADBURST_AKL 13
#define BADBURST_CLK 14
#define BADBURST_KSM 15
#define BADBURST_KAB 16
#define BADBURST_NOEPS 17
#define BADBURST_PHYS 18
#define BADBURST_SPARE1 19
#define BADBURST_SPARE2 20
#define BADBURST_SPARE3 21
#define BADBURST_SPARE4 22
#define BADBURST_SIZE 23

/* Offsets for structure TimeOffset */
#define TIMEOFFSET_VERSION 0
#define TIMEOFFSET_TAG 1
#define TIMEOFFSET_AKS 2
#define TIMEOFFSET_AKL 3
#define TIMEOFFSET_HOD 4
#define TIMEOFFSET_NHO 5
#define TIMEOFFSET_DCH 6
#define TIMEOFFSET_LKR 7
#define TIMEOFFSET_HAC 8
#define TIMEOFFSET_MUV 9
#define TIMEOFFSET_LKRTAG 10
#define TIMEOFFSET_LKRNHOD 11
#define TIMEOFFSET_LKRAKL 12
#define TIMEOFFSET_LKRHAC 13
#define TIMEOFFSET_KABPLUS 14
#define TIMEOFFSET_KABMINUS 15
#define TIMEOFFSET_SIZE 16

/* Offsets for structure superTimeOffset */
#define SUPERTIMEOFFSET_VERSION 0
#define SUPERTIMEOFFSET_TAG 1
#define SUPERTIMEOFFSET_AKS 2
#define SUPERTIMEOFFSET_KAB 3
#define SUPERTIMEOFFSET_NMV 4
#define SUPERTIMEOFFSET_AKL 5
#define SUPERTIMEOFFSET_HOD 6
#define SUPERTIMEOFFSET_NHO 7
#define SUPERTIMEOFFSET_DCH 8
#define SUPERTIMEOFFSET_LKR 9
#define SUPERTIMEOFFSET_HAC 10
#define SUPERTIMEOFFSET_MUV 11
#define SUPERTIMEOFFSET_LKRTAG 12
#define SUPERTIMEOFFSET_LKRNHOD 13
#define SUPERTIMEOFFSET_LKRAKL 14
#define SUPERTIMEOFFSET_LKRHAC 15
#define SUPERTIMEOFFSET_KABPLUS 16
#define SUPERTIMEOFFSET_KABMINUS 17
#define SUPERTIMEOFFSET_SIZE 18

/* Offsets for structure anatocall */
#define ANATOCALL_SELCHARGED 0
#define ANATOCALL_SEL2PI0 1
#define ANATOCALL_SEL3PI0 2
#define ANATOCALL_BLUEFIELD 3
#define ANATOCALL_LKRPEDCOR 4
#define ANATOCALL_LKRPOSCOR 5
#define ANATOCALL_LKRSHARING 6
#define ANATOCALL_HODOTIME 7
#define ANATOCALL_NHODTIME 8
#define ANATOCALL_LKRTIME 9
#define ANATOCALL_TAGTIME 10
#define ANATOCALL_AKSFLAG 11
#define ANATOCALL_MUON_REC 12
#define ANATOCALL_MUON_REJECT 13
#define ANATOCALL_GEOMCOR 14
#define ANATOCALL_MAGNETCOR 15
#define ANATOCALL_NEWCHARGED 16
#define ANATOCALL_MUON_TRACKREC 17
#define ANATOCALL_MUON_VTXREC 18
#define ANATOCALL_LKRCALCOR 19
#define ANATOCALL_LKRCALCOR1 20
#define ANATOCALL_LKRCALCOR2 21
#define ANATOCALL_LKRCALCOR3 22
#define ANATOCALL_LKRCALHI2K 23
#define ANATOCALL_SEL2GAM 24
#define ANATOCALL_SIZE 25

/* Offsets for structure Burst */
#define BURST_MAJORVER 1
#define BURST_MINORVER 2
#define BURST_PATCH 3
#define BURST_TIME 4
#define BURST_HEPDB 5
#define BURST_BRTYPE 25
#define BURST_BMTYPE 26
#define BURST_INTENSITY 27
#define BURST_NRUN 28
#define BURST_NEVENT 29
#define BURST_DATASET 30
#define BURST_KSMSCA 31
#define BURST_NHOSCA 63
#define BURST_HODVSCA 95
#define BURST_HODHSCA 159
#define BURST_LOGIC 223
#define BURST_SYPS 351
#define BURST_TSSCA 383
#define BURST_TS 507
#define BURST_XOFFBURSTLEN 755
#define BURST_XOFFDCH 756
#define BURST_XOFFLKR 762
#define BURST_XOFFNUT 768
#define BURST_XOFFHAC 774
#define BURST_XOFFAKL 780
#define BURST_XOFFTAG 786
#define BURST_XOFFHOD 792
#define BURST_XOFFMUV 798
#define BURST_TAGCLK 804
#define BURST_BEAMNS 807
#define BURST_BEAMS 861
#define BURST_BM 877
#define BURST_BM01 4112
#define BURST_DM 10547
#define BURST_LKRCALIB 10549
#define BURST_MUVSCAL 10580
#define BURST_NTRIGWORD 10582
#define BURST_TRIGWORD 10583
#define BURST_NTIMESTAMP 80583
#define BURST_TIMESTAMP 80584
#define BURST_NDCHDECERROR 150584
#define BURST_DCHDECERROR 150585
#define BURST_NLKRHACDECERROR 220585
#define BURST_LKRHACDECERROR 220586
#define BURST_NCHARGEDINFO 290586
#define BURST_CHARGEDINFO 290587
#define BURST_NNEUTRALINFO 360587
#define BURST_NEUTRALINFO 360588
#define BURST_BADB 430588
#define BURST_CHAMBERDZ 430611
#define BURST_TOFFST 430615
#define BURST_CALLANAROUTINE 430633
#define BURST_TOCALL 430634
#define BURST_GETEOBBEFORE 430659
#define BURST_DBERR 430660
#define BURST_SIZE 430661

/* Offsets for structure L3errorcounter */
#define L3ERRORCOUNTER_ERROR 0
#define L3ERRORCOUNTER_DECEVT 1
#define L3ERRORCOUNTER_DECTAG 2
#define L3ERRORCOUNTER_DECAKS 3
#define L3ERRORCOUNTER_DECAKL 4
#define L3ERRORCOUNTER_DECDCH 5
#define L3ERRORCOUNTER_DECHOD 6
#define L3ERRORCOUNTER_DECNHO 7
#define L3ERRORCOUNTER_DECLKR 8
#define L3ERRORCOUNTER_DECHAC 9
#define L3ERRORCOUNTER_DECMUV 10
#define L3ERRORCOUNTER_DECPAT 11
#define L3ERRORCOUNTER_DECNUT 12
#define L3ERRORCOUNTER_DECL3 13
#define L3ERRORCOUNTER_RECTAG 14
#define L3ERRORCOUNTER_RECAKS 15
#define L3ERRORCOUNTER_RECAKL 16
#define L3ERRORCOUNTER_RECDCH 17
#define L3ERRORCOUNTER_RECHOD 18
#define L3ERRORCOUNTER_RECNHO 19
#define L3ERRORCOUNTER_RECLKR 20
#define L3ERRORCOUNTER_RECHAC 21
#define L3ERRORCOUNTER_RECMUV 22
#define L3ERRORCOUNTER_RECBTH 23
#define L3ERRORCOUNTER_COMDCH_NODCH 24
#define L3ERRORCOUNTER_COMEP_NODCH 25
#define L3ERRORCOUNTER_COMEP_NOLKR 26
#define L3ERRORCOUNTER_COMEP_DOUBLECLUS 27
#define L3ERRORCOUNTER_COMEP_NOCLUS 28
#define L3ERRORCOUNTER_COMEP_SAMECLUS 29
#define L3ERRORCOUNTER_COMMBOX_NODCH 30
#define L3ERRORCOUNTER_COMNUT_NOLKR 31
#define L3ERRORCOUNTER_COML3B_NOLKR 32
#define L3ERRORCOUNTER_SPARE 33
#define L3ERRORCOUNTER_SIZE 34

/* Offsets for structure decResult */
#define DECRESULT_CODE 0
#define DECRESULT_ECHAN 1
#define DECRESULT_LOG 2
#define DECRESULT_NERR 3
#define DECRESULT_SATFLAG 4
#define DECRESULT_EVTNO 5
#define DECRESULT_TS 6
#define DECRESULT_X1 7
#define DECRESULT_X2 8
#define DECRESULT_SIZE 9

/* Offsets for structure anaerrdec */
#define ANAERRDEC_NDECRES 0
#define ANAERRDEC_DECRES 1
#define ANAERRDEC_SIZE 18001

/* Offsets for structure pisaCounter */
#define PISACOUNTER_COUNTS 0
#define PISACOUNTER_SIZE 64

/* Offsets for structure pisaCounterSample */
#define PISACOUNTERSAMPLE_CLOCK 0
#define PISACOUNTERSAMPLE_PHASE 1
#define PISACOUNTERSAMPLE_EFFSPILL 2
#define PISACOUNTERSAMPLE_MOM0_JURA 8
#define PISACOUNTERSAMPLE_MOM0_SALEVE 9
#define PISACOUNTERSAMPLE_MOM1_JURA 10
#define PISACOUNTERSAMPLE_MOM1_SALEVE 12
#define PISACOUNTERSAMPLE_MOM2_JURA 14
#define PISACOUNTERSAMPLE_MOM2_SALEVE 16
#define PISACOUNTERSAMPLE_SIZE 18

/* Offsets for structure pisaMonitors */
#define PISAMONITORS_TIME 0
#define PISAMONITORS_NSAMPLE 1
#define PISAMONITORS_SAMPLE 2
#define PISAMONITORS_MAINZ 1802
#define PISAMONITORS_NMONJURA 1818
#define PISAMONITORS_MONJURA 1819
#define PISAMONITORS_NMONSALEVE 2459
#define PISAMONITORS_MONSALEVE 2460
#define PISAMONITORS_NMONAUX 3100
#define PISAMONITORS_MONAUX 3101
#define PISAMONITORS_SIZE 3741

/* Offsets for structure EoBMagnet */
#define EOBMAGNET_TIME 0
#define EOBMAGNET_HALLVSOB 1
#define EOBMAGNET_HALLTSOB 7
#define EOBMAGNET_HALLVEOB 13
#define EOBMAGNET_HALLTEOB 19
#define EOBMAGNET_VOLTMETERSOB 25
#define EOBMAGNET_VOLTMETEREOB 26
#define EOBMAGNET_SIZE 27

/* Offsets for structure EndofBurst */
#define ENDOFBURST_NEVENT 1
#define ENDOFBURST_NWRITE 2
#define ENDOFBURST_NKILL 3
#define ENDOFBURST_STATUS 4
#define ENDOFBURST_SGNNRESET 5
#define ENDOFBURST_SGNINEFF 8
#define ENDOFBURST_SGNEFF 392
#define ENDOFBURST_SGNBERR 776
#define ENDOFBURST_SGNBADBIT 796
#define ENDOFBURST_L3ERRCTR 797
#define ENDOFBURST_NEVENTLIST 831
#define ENDOFBURST_NTRIGWORD 832
#define ENDOFBURST_TRIGWORD 833
#define ENDOFBURST_NTIMESTAMP 70833
#define ENDOFBURST_TIMESTAMP 70834
#define ENDOFBURST_NDCHDECERROR 140834
#define ENDOFBURST_DCHDECERROR 140835
#define ENDOFBURST_NLKRHACDECERROR 210835
#define ENDOFBURST_LKRHACDECERROR 210836
#define ENDOFBURST_NCHARGEDINFO 280836
#define ENDOFBURST_CHARGEDINFO 280837
#define ENDOFBURST_NNEUTRALINFO 350837
#define ENDOFBURST_NEUTRALINFO 350838
#define ENDOFBURST_NPROCERROR 420838
#define ENDOFBURST_PROCERROR 420839
#define ENDOFBURST_NPROCERRORREPRO 430839
#define ENDOFBURST_PROCERRORREPRO 430840
#define ENDOFBURST_MAGNETPROBES 440840
#define ENDOFBURST_PISAMON 440867
#define ENDOFBURST_AERRDEC 444608
#define ENDOFBURST_L3SPARE_INT 462609
#define ENDOFBURST_L3SPARE_FLOAT 462689
#define ENDOFBURST_SIZE 462709

/* Offsets for structure FHeader */
#define FHEADER_MAJORVER 0
#define FHEADER_MINORVER 1
#define FHEADER_PATCH 2
#define FHEADER_FTYPE 3
#define FHEADER_FLAGS 4
#define FHEADER_SIZE 8

/* Offsets for structure FExtHeader */
#define FEXTHEADER_SQL_DB_VER 0
#define FEXTHEADER_SQL_DB_UPD 1
#define FEXTHEADER_SPARE 2
#define FEXTHEADER_SIZE 6

/* Offsets for structure FTrailer */
#define FTRAILER_NBURSTS 0
#define FTRAILER_STATUS 1
#define FTRAILER_FLAGS 2
#define FTRAILER_SIZE 6

/* Offsets for structure ke3Event */
#define KE3EVENT_N 1
#define KE3EVENT_TIMESTAMP 2
#define KE3EVENT_ECELL 3
#define KE3EVENT_FCELL 52
#define KE3EVENT_ADC 101
#define KE3EVENT_IXELEC 146
#define KE3EVENT_IYELEC 147
#define KE3EVENT_XCLUS 148
#define KE3EVENT_YCLUS 149
#define KE3EVENT_EELEC 150
#define KE3EVENT_PELEC 151
#define KE3EVENT_XELEC 152
#define KE3EVENT_YELEC 153
#define KE3EVENT_APXELEC 154
#define KE3EVENT_APYELEC 155
#define KE3EVENT_ERAW 156
#define KE3EVENT_CELLSREAD 157
#define KE3EVENT_SPACHACORR 158
#define KE3EVENT_ECORRKE3 159
#define KE3EVENT_E2SAMP7 160
#define KE3EVENT_EHAC 161
#define KE3EVENT_DISTHAC 162
#define KE3EVENT_NPMUV 163
#define KE3EVENT_ECLUNEAR 164
#define KE3EVENT_IDCLUNEAR 165
#define KE3EVENT_XCLUNEAR 166
#define KE3EVENT_YCLUNEAR 167
#define KE3EVENT_PPION 168
#define KE3EVENT_XPION 169
#define KE3EVENT_YPION 170
#define KE3EVENT_ZVERTEX 171
#define KE3EVENT_SPNT 172
#define KE3EVENT_SIZE 184

/* Offsets for structure kmu3Event */
#define KMU3EVENT_NNUT 1
#define KMU3EVENT_NUT 2
#define KMU3EVENT_CMPEVT 149
#define KMU3EVENT_SIZE 920666

/* Offsets for structure mcPlaneTrak */
#define MCPLANETRAK_ICODE 0
#define MCPLANETRAK_XYZ 1
#define MCPLANETRAK_ZPLANE 4
#define MCPLANETRAK_DXDZ 5
#define MCPLANETRAK_DYDZ 6
#define MCPLANETRAK_EDEP 7
#define MCPLANETRAK_ACCEPT 8
#define MCPLANETRAK_SIZE 9

/* Offsets for structure mcParticle */
#define MCPARTICLE_TYPE 0
#define MCPARTICLE_P 1
#define MCPARTICLE_PVERTEX 5
#define MCPARTICLE_DVERTEX 8
#define MCPARTICLE_SPIN 11
#define MCPARTICLE_XBMAG 14
#define MCPARTICLE_XAMAG 17
#define MCPARTICLE_PBMAG 20
#define MCPARTICLE_PAMAG 23
#define MCPARTICLE_ICODES 26
#define MCPARTICLE_NPLANE 27
#define MCPARTICLE_PLANE 28
#define MCPARTICLE_SIZE 208

/* Offsets for structure mcSIM */
#define MCSIM_MCTYPE 0
#define MCSIM_MCVERSION 1
#define MCSIM_GEOVERSION 2
#define MCSIM_SHWVERSION 3
#define MCSIM_SIMYEAR 4
#define MCSIM_ACCRATE 5
#define MCSIM_KSKLRATIO 6
#define MCSIM_CNRATIO 7
#define MCSIM_RANDSEED 8
#define MCSIM_MCWORD 11
#define MCSIM_NASIM 15
#define MCSIM_TIME 19
#define MCSIM_MAGNETSIM 20
#define MCSIM_OPTIONS 21
#define MCSIM_NPART 22
#define MCSIM_PART 23
#define MCSIM_SIZE 4183

/* Offsets for structure mcEvent */
#define MCEVENT_NMCSIM 1
#define MCEVENT_MCSIM 2
#define MCEVENT_CMPEVT 20917
#define MCEVENT_SIZE 941434

/* Offsets for structure DETstatus */
#define DETSTATUS_AKL 0
#define DETSTATUS_DCH 1
#define DETSTATUS_HOD 2
#define DETSTATUS_HAC 3
#define DETSTATUS_LKR 4
#define DETSTATUS_KAB				 5
#define DETSTATUS_NHO 6
#define DETSTATUS_MUV 7
#define DETSTATUS_MBX 8
#define DETSTATUS_NTR 9
#define DETSTATUS_LV3 10
#define DETSTATUS_LV3TRIG 11
#define DETSTATUS_LV3TRIGRARE 12
#define DETSTATUS_LV3ABTRIG 13
#define DETSTATUS_LV3ATRIGRARE 14
#define DETSTATUS_LV3BTRIGRARE 15
#define DETSTATUS_CHTREFF 16
#define DETSTATUS_SIZE 26

/* Offsets for structure KABstrack */
#define KABSTRACK_P 0
#define KABSTRACK_Q 1
#define KABSTRACK_UPORDOWN 2
#define KABSTRACK_PERR 3
#define KABSTRACK_CHI2 4
#define KABSTRACK_X 5
#define KABSTRACK_Y 6
#define KABSTRACK_XUORD 7
#define KABSTRACK_YUORD 8
#define KABSTRACK_TIME 9
#define KABSTRACK_TIMEUORD 10
#define KABSTRACK_TIMEST2 11
#define KABSTRACK_DXDZ 12
#define KABSTRACK_DYDZ 13
#define KABSTRACK_SIGXX 14
#define KABSTRACK_SIGYY 15
#define KABSTRACK_SIGTT 16
#define KABSTRACK_SIGDXDX 17
#define KABSTRACK_SIGDYDY 18
#define KABSTRACK_RECFLAG 19
#define KABSTRACK_ANAVAR 20
#define KABSTRACK_ANAFLAG 40
#define KABSTRACK_SIZE 45

/* Offsets for structure trak */
#define TRAK_P 0
#define TRAK_Q 1
#define TRAK_QUALITY 2
#define TRAK_CHI2 3
#define TRAK_BX 4
#define TRAK_BY 5
#define TRAK_BDXDZ 6
#define TRAK_BDYDZ 7
#define TRAK_X 8
#define TRAK_Y 9
#define TRAK_DXDZ 10
#define TRAK_DYDZ 11
#define TRAK_PERR 12
#define TRAK_SIGXX 13
#define TRAK_SIGYY 14
#define TRAK_SIGDXDX 15
#define TRAK_SIGDYDY 16
#define TRAK_SIGXDX 17
#define TRAK_SIGXY 18
#define TRAK_SIGDXY 19
#define TRAK_SIGXDY 20
#define TRAK_SIGDXDY 21
#define TRAK_SIGYDY 22
#define TRAK_TIME 23
#define TRAK_HODTIME 24
#define TRAK_HODSTATUS 25
#define TRAK_AKLTIME 26
#define TRAK_AKLTIME67 27
#define TRAK_AKLFLAG 28
#define TRAK_IMUON 29
#define TRAK_IHAC 30
#define TRAK_ICLUS 31
#define TRAK_DDEADCELL 32
#define TRAK_HITPATTERN 33
#define TRAK_EFFICIENCY 34
#define TRAK_SPARE 36
#define TRAK_SIZE 41

/* Offsets for structure cluster */
#define CLUSTER_ENERGY 0
#define CLUSTER_X 1
#define CLUSTER_Y 2
#define CLUSTER_TIME 3
#define CLUSTER_HACTIME 4
#define CLUSTER_HODTIME 5
#define CLUSTER_AKLTIME 6
#define CLUSTER_AKLTIME67 7
#define CLUSTER_AKLFLAG 8
#define CLUSTER_DDEADCELL 9
#define CLUSTER_STATUS 10
#define CLUSTER_ITRACK 11
#define CLUSTER_RMSX 12
#define CLUSTER_RMSY 13
#define CLUSTER_MCTAILCORR 14
#define CLUSTER_SPARE 15
#define CLUSTER_SIZE 20

/* Offsets for structure vtxtracks */
#define VTXTRACKS_ITRACK 0
#define VTXTRACKS_BDXDZ 1
#define VTXTRACKS_BDYDZ 2
#define VTXTRACKS_SIZE 3

/* Offsets for structure SCvertex */
#define SCVERTEX_NVTXTRACK 0
#define SCVERTEX_VTXTRACK 1
#define SCVERTEX_CHARGE 22
#define SCVERTEX_CDA 23
#define SCVERTEX_COG 24
#define SCVERTEX_CHI2 25
#define SCVERTEX_X 26
#define SCVERTEX_Y 27
#define SCVERTEX_Z 28
#define SCVERTEX_TVTX 29
#define SCVERTEX_TVTXHODO 30
#define SCVERTEX_HACTIME 31
#define SCVERTEX_AKLTIME 32
#define SCVERTEX_AKLTIME67 33
#define SCVERTEX_AKLFLAG 34
#define SCVERTEX_ANAVAR 35
#define SCVERTEX_ANAFLAG 40
#define SCVERTEX_SIZE 45

/* Offsets for structure muon */
#define MUON_X 0
#define MUON_Y 1
#define MUON_TIME 2
#define MUON_CHI2 3
#define MUON_STATUS 4
#define MUON_PLANE 5
#define MUON_ITRK 7
#define MUON_SIZE 8

/* Offsets for structure pmuon */
#define PMUON_TIME 0
#define PMUON_CHANNEL 1
#define PMUON_SIZE 2

/* Offsets for structure hacclus */
#define HACCLUS_ENERGY 0
#define HACCLUS_X 1
#define HACCLUS_Y 2
#define HACCLUS_TIME 3
#define HACCLUS_BFRATIO 4
#define HACCLUS_SIZE 5

/* Offsets for structure SCDCHmult */
#define SCDCHMULT_MBXPLANEEFF 0
#define SCDCHMULT_L1TRK24EFF 6
#define SCDCHMULT_DCHSNOWERR 8
#define SCDCHMULT_MBXMULT 10
#define SCDCHMULT_TRK24ON 11
#define SCDCHMULT_SIZE 12

/* Offsets for structure PUtslice */
#define PUTSLICE_CHAN 0
#define PUTSLICE_SIZE 16

/* Offsets for structure MaChit */
#define MACHIT_COUNTER 0
#define MACHIT_PHEIGHT 1
#define MACHIT_TIME 2
#define MACHIT_PDSFLAG 3
#define MACHIT_SIZE 4

/* Offsets for structure SRNDMsummary */
#define SRNDMSUMMARY_TYPE 0
#define SRNDMSUMMARY_TIMESTAMP 1
#define SRNDMSUMMARY_RUN 2
#define SRNDMSUMMARY_BURST 3
#define SRNDMSUMMARY_NUSED 4
#define SRNDMSUMMARY_SPSPHASE 5
#define SRNDMSUMMARY_MAINPHASE 6
#define SRNDMSUMMARY_TOVRFLW 7
#define SRNDMSUMMARY_KLMONDNDT 71
#define SRNDMSUMMARY_KSMONDNDT 72
#define SRNDMSUMMARY_QXDNDT 73
#define SRNDMSUMMARY_SIZE 74

/* Offsets for structure superCmpEvent */
#define SUPERCMPEVENT_DBERR 1
#define SUPERCMPEVENT_CMPSTATUS 2
#define SUPERCMPEVENT_FLAGCORR 3
#define SUPERCMPEVENT_CMPFILTER 4
#define SUPERCMPEVENT_DETSTATUS 5
#define SUPERCMPEVENT_RNDM 31
#define SUPERCMPEVENT_NEVT 105
#define SUPERCMPEVENT_TRIGWORD 106
#define SUPERCMPEVENT_TIMESTAMP 107
#define SUPERCMPEVENT_NTRIGBEF 108
#define SUPERCMPEVENT_TIMETOPREV 109
#define SUPERCMPEVENT_SPSPHASE 110
#define SUPERCMPEVENT_MAINSPHASE 111
#define SUPERCMPEVENT_SPSPHASERAW 112
#define SUPERCMPEVENT_MAINSPHASERAW 113
#define SUPERCMPEVENT_KLMONDNDT 114
#define SUPERCMPEVENT_QXDNDT 115
#define SUPERCMPEVENT_PU 116
#define SUPERCMPEVENT_NMCH 276
#define SUPERCMPEVENT_MCH 277
#define SUPERCMPEVENT_LKRDOWNSCALED 357
#define SUPERCMPEVENT_LKRENERGY 358
#define SUPERCMPEVENT_HACENERGY 359
#define SUPERCMPEVENT_NKABSTRAK 360
#define SUPERCMPEVENT_KABSTRAK 361
#define SUPERCMPEVENT_NTRACK 2611
#define SUPERCMPEVENT_TRACK 2612
#define SUPERCMPEVENT_NVTX 4252
#define SUPERCMPEVENT_VTX 4253
#define SUPERCMPEVENT_NMUON 8753
#define SUPERCMPEVENT_MUON 8754
#define SUPERCMPEVENT_NPMUON 8850
#define SUPERCMPEVENT_PMUON 8851
#define SUPERCMPEVENT_NHACCLUS 8963
#define SUPERCMPEVENT_HACCLUS 8964
#define SUPERCMPEVENT_NCLUSTER 9089
#define SUPERCMPEVENT_CLUSTER 9090
#define SUPERCMPEVENT_SCDCHEFFMULT 9590
#define SUPERCMPEVENT_TSPREV 9602
#define SUPERCMPEVENT_TSNEXT 9603
#define SUPERCMPEVENT_TWPREV 9604
#define SUPERCMPEVENT_TWNEXT 9605
#define SUPERCMPEVENT_SPAREINT 9606
#define SUPERCMPEVENT_SPAREFLOAT 9608
#define SUPERCMPEVENT_SIZE 9610

/* Offsets for structure STSscal */
#define STSSCAL_NSCALER 0
#define STSSCAL_SCALER 1
#define STSSCAL_SIZE 101

/* Offsets for structure SL2TSscal */
#define SL2TSSCAL_NSCALER 0
#define SL2TSSCAL_SCALER 1
#define SL2TSSCAL_SIZE 21

/* Offsets for structure superBurst */
#define SUPERBURST_MAJORVER 1
#define SUPERBURST_MINORVER 2
#define SUPERBURST_PATCH 3
#define SUPERBURST_TIME 4
#define SUPERBURST_BRTYPE 5
#define SUPERBURST_NRUN 6
#define SUPERBURST_NTRIGWORD 7
#define SUPERBURST_INTENSITY 8
#define SUPERBURST_INTENSITYT4 9
#define SUPERBURST_CTAUORIGIN 10
#define SUPERBURST_TOFFSTVER 11
#define SUPERBURST_MNP33CURRENT 12
#define SUPERBURST_BEND1CURRENT 13
#define SUPERBURST_FLAGS 14
#define SUPERBURST_TSSCAL 15
#define SUPERBURST_L2TSSCAL 116
#define SUPERBURST_DATASET 137
#define SUPERBURST_TOFFST 138
#define SUPERBURST_BADB 156
#define SUPERBURST_DBERR 179
#define SUPERBURST_SIZE 180

/* Offsets for structure superPisaCounter */
#define SUPERPISACOUNTER_AVERAGE 0
#define SUPERPISACOUNTER_STDDEV 64
#define SUPERPISACOUNTER_SIZE 128

/* Offsets for structure superPisaMonitors */
#define SUPERPISAMONITORS_JURACOUNTS 0
#define SUPERPISAMONITORS_SALEVECOUNTS 64
#define SUPERPISAMONITORS_AUXCOUNTS 128
#define SUPERPISAMONITORS_SIZE 192

/* Offsets for structure superPisaMonitors04 */
#define SUPERPISAMONITORS04_TIME 0
#define SUPERPISAMONITORS04_NSAMPLE 1
#define SUPERPISAMONITORS04_SAMPLE 2
#define SUPERPISAMONITORS04_MAINZ 1802
#define SUPERPISAMONITORS04_SIZE 1818

/* Offsets for structure superEndofBurst */
#define SUPERENDOFBURST_MAGIC 1
#define SUPERENDOFBURST_DCHPLANEHIT 2
#define SUPERENDOFBURST_DCHCARDHIT 34
#define SUPERENDOFBURST_SMAGNETPROBES 546
#define SUPERENDOFBURST_SPISAMON 573
#define SUPERENDOFBURST_PISAMON 765
#define SUPERENDOFBURST_SIZE 2583

/* Offsets for structure superMcParticle */
#define SUPERMCPARTICLE_TYPE 0
#define SUPERMCPARTICLE_P 1
#define SUPERMCPARTICLE_PVERTEX 5
#define SUPERMCPARTICLE_DVERTEX 8
#define SUPERMCPARTICLE_SPIN 11
#define SUPERMCPARTICLE_SIZE 14

/* Offsets for structure superMcDecay */
#define SUPERMCDECAY_KTYPE 0
#define SUPERMCDECAY_DTYPE 1
#define SUPERMCDECAY_DVERTEX 2
#define SUPERMCDECAY_P 5
#define SUPERMCDECAY_SIZE 9

/* Offsets for structure superMcEvent */
#define SUPERMCEVENT_DECAY 1
#define SUPERMCEVENT_NPART 10
#define SUPERMCEVENT_PART 11
#define SUPERMCEVENT_SCMPEVT 291
#define SUPERMCEVENT_SIZE 9901

/* Offsets for structure hyperBurst */
#define HYPERBURST_MAJORVER 1
#define HYPERBURST_MINORVER 2
#define HYPERBURST_BADB 3
#define HYPERBURST_TOFFST 26
#define HYPERBURST_TIME 44
#define HYPERBURST_BRTYPE 45
#define HYPERBURST_NRUN 46
#define HYPERBURST_SAMPLE 47
#define HYPERBURST_FLAG 48
#define HYPERBURST_SPARE 49
#define HYPERBURST_SIZE 51

/* Offsets for structure hyperKabTrk */
#define HYPERKABTRK_P 0
#define HYPERKABTRK_Q 1
#define HYPERKABTRK_UPORDOWN 2
#define HYPERKABTRK_PERR 3
#define HYPERKABTRK_CHI2 4
#define HYPERKABTRK_X 5
#define HYPERKABTRK_Y 6
#define HYPERKABTRK_YUORD 7
#define HYPERKABTRK_TIME 8
#define HYPERKABTRK_DXDZ 9
#define HYPERKABTRK_DYDZ 10
#define HYPERKABTRK_SIZE 11

/* Offsets for structure hyperCluster */
#define HYPERCLUSTER_ENERGY 0
#define HYPERCLUSTER_X 1
#define HYPERCLUSTER_Y 2
#define HYPERCLUSTER_TIME			 3
#define HYPERCLUSTER_RMSX 4
#define HYPERCLUSTER_RMSY 5
#define HYPERCLUSTER_DDEADCELL 6
#define HYPERCLUSTER_DTRACK 7
#define HYPERCLUSTER_FLAG 8
#define HYPERCLUSTER_SPARE 9
#define HYPERCLUSTER_SIZE 11

/* Offsets for structure hyperTrack */
#define HYPERTRACK_Q 0
#define HYPERTRACK_P 1
#define HYPERTRACK_PERR 2
#define HYPERTRACK_TIME 3
#define HYPERTRACK_HODOTIME 4
#define HYPERTRACK_BX 5
#define HYPERTRACK_BY 6
#define HYPERTRACK_X 7
#define HYPERTRACK_Y 8
#define HYPERTRACK_BDXDZ 9
#define HYPERTRACK_BDYDZ 10
#define HYPERTRACK_NBFBDXDZ 11
#define HYPERTRACK_NBFBDYDZ 12
#define HYPERTRACK_DXDZ 13
#define HYPERTRACK_DYDZ 14
#define HYPERTRACK_EOP 15
#define HYPERTRACK_FLAG 16
#define HYPERTRACK_SPARE 17
#define HYPERTRACK_SIZE 19

/* Offsets for structure hyperVertex */
#define HYPERVERTEX_Q 0
#define HYPERVERTEX_MASS 1
#define HYPERVERTEX_P 2
#define HYPERVERTEX_CDA 3
#define HYPERVERTEX_POS 4
#define HYPERVERTEX_SPARE 7
#define HYPERVERTEX_SIZE 9

/* Offsets for structure hyperMcParticle */
#define HYPERMCPARTICLE_TYPE 0
#define HYPERMCPARTICLE_P 1
#define HYPERMCPARTICLE_PVERTEX 5
#define HYPERMCPARTICLE_DVERTEX 8
#define HYPERMCPARTICLE_SIZE 11

/* Offsets for structure hyperCmpEvent */
#define HYPERCMPEVENT_DBERR 1
#define HYPERCMPEVENT_FLAG 2
#define HYPERCMPEVENT_TIMESTAMP 3
#define HYPERCMPEVENT_SPSPHASE 4
#define HYPERCMPEVENT_MAINSPHASE 5
#define HYPERCMPEVENT_TRIGWORD 6
#define HYPERCMPEVENT_PUPACK 7
#define HYPERCMPEVENT_PU04 10
#define HYPERCMPEVENT_PU14 13
#define HYPERCMPEVENT_PU06 16
#define HYPERCMPEVENT_NCLUSTER 19
#define HYPERCMPEVENT_CLUSTER 20
#define HYPERCMPEVENT_NTRACK 64
#define HYPERCMPEVENT_TRACK 65
#define HYPERCMPEVENT_VTX 122
#define HYPERCMPEVENT_KABTRK 131
#define HYPERCMPEVENT_NMCPART 142
#define HYPERCMPEVENT_MCPART 143
#define HYPERCMPEVENT_SPARE 363
#define HYPERCMPEVENT_SIZE 365

/* Offsets for structure INTAKLhit */
#define INTAKLHIT_POCKET 0
#define INTAKLHIT_LAYER 1
#define INTAKLHIT_COUNTER 2
#define INTAKLHIT_MIPS 3
#define INTAKLHIT_TIME 4
#define INTAKLHIT_ONTFLAG 5
#define INTAKLHIT_SIZE 6

/* Offsets for structure INTRNDMsummary */
#define INTRNDMSUMMARY_TYPE 0
#define INTRNDMSUMMARY_TIMESTAMP 1
#define INTRNDMSUMMARY_RUN 2
#define INTRNDMSUMMARY_BURST 3
#define INTRNDMSUMMARY_NUSED 4
#define INTRNDMSUMMARY_SPSPHASE 5
#define INTRNDMSUMMARY_MAINPHASE 6
#define INTRNDMSUMMARY_TOVRFLW 7
#define INTRNDMSUMMARY_KLMONDNDT 71
#define INTRNDMSUMMARY_QXDNDT 72
#define INTRNDMSUMMARY_SIZE 73

/* Offsets for structure INTKABstrack */
#define INTKABSTRACK_P 0
#define INTKABSTRACK_Q 1
#define INTKABSTRACK_UPORDOWN 2
#define INTKABSTRACK_PERR 3
#define INTKABSTRACK_CHI2 4
#define INTKABSTRACK_X 5
#define INTKABSTRACK_Y 6
#define INTKABSTRACK_XUORD 7
#define INTKABSTRACK_YUORD 8
#define INTKABSTRACK_TIME 9
#define INTKABSTRACK_TIMEUORD 10
#define INTKABSTRACK_TIMEST2 11
#define INTKABSTRACK_DXDZ 12
#define INTKABSTRACK_DYDZ 13
#define INTKABSTRACK_SIGXX 14
#define INTKABSTRACK_SIGYY 15
#define INTKABSTRACK_SIGTT 16
#define INTKABSTRACK_SIGDXDX 17
#define INTKABSTRACK_SIGDYDY 18
#define INTKABSTRACK_RECFLAG 19
#define INTKABSTRACK_ANAVAR 20
#define INTKABSTRACK_ANAFLAG 40
#define INTKABSTRACK_SIZE 45

/* Offsets for structure INTtrak */
#define INTTRAK_P 0
#define INTTRAK_Q 1
#define INTTRAK_QUALITY 2
#define INTTRAK_CHI2 3
#define INTTRAK_BX 4
#define INTTRAK_BY 5
#define INTTRAK_BDXDZ 6
#define INTTRAK_BDYDZ 7
#define INTTRAK_X 8
#define INTTRAK_Y 9
#define INTTRAK_DXDZ 10
#define INTTRAK_DYDZ 11
#define INTTRAK_PERR 12
#define INTTRAK_SIGXX 13
#define INTTRAK_SIGYY 14
#define INTTRAK_SIGDXDX 15
#define INTTRAK_SIGDYDY 16
#define INTTRAK_SIGXDX 17
#define INTTRAK_SIGXY 18
#define INTTRAK_SIGDXY 19
#define INTTRAK_SIGXDY 20
#define INTTRAK_SIGDXDY 21
#define INTTRAK_SIGYDY 22
#define INTTRAK_TIME 23
#define INTTRAK_HODTIME 24
#define INTTRAK_AKLTIME 25
#define INTTRAK_AKLTIME67 26
#define INTTRAK_AKLFLAG 27
#define INTTRAK_IMUON 28
#define INTTRAK_DDEADCELL 29
#define INTTRAK_IHAC 30
#define INTTRAK_ICLUS 31
#define INTTRAK_HODSTATUS 32
#define INTTRAK_HITPATTERN 33
#define INTTRAK_EFFICIENCY 34
#define INTTRAK_SPARE 36
#define INTTRAK_SIZE 41

/* Offsets for structure INTcluster */
#define INTCLUSTER_ENERGY 0
#define INTCLUSTER_X 1
#define INTCLUSTER_Y 2
#define INTCLUSTER_TIME 3
#define INTCLUSTER_HACTIME 4
#define INTCLUSTER_HODTIME 5
#define INTCLUSTER_AKLTIME 6
#define INTCLUSTER_AKLTIME67 7
#define INTCLUSTER_AKLFLAG 8
#define INTCLUSTER_DDEADCELL 9
#define INTCLUSTER_STATUS 10
#define INTCLUSTER_ITRACK 11
#define INTCLUSTER_RMSX 12
#define INTCLUSTER_RMSY 13
#define INTCLUSTER_MCTAILCORR 14
#define INTCLUSTER_SPARE 15
#define INTCLUSTER_SIZE 20

/* Offsets for structure INTSCvertex */
#define INTSCVERTEX_NVTXTRACK 0
#define INTSCVERTEX_VTXTRACK 1
#define INTSCVERTEX_CHARGE 22
#define INTSCVERTEX_CDA 23
#define INTSCVERTEX_COG 24
#define INTSCVERTEX_CHI2 25
#define INTSCVERTEX_X 26
#define INTSCVERTEX_Y 27
#define INTSCVERTEX_Z 28
#define INTSCVERTEX_TVTX 29
#define INTSCVERTEX_TVTXHODO 30
#define INTSCVERTEX_HACTIME 31
#define INTSCVERTEX_AKLTIME 32
#define INTSCVERTEX_AKLTIME67 33
#define INTSCVERTEX_AKLFLAG 34
#define INTSCVERTEX_SIZE 35

/* Offsets for structure INTmuon */
#define INTMUON_X 0
#define INTMUON_Y 1
#define INTMUON_TIME 2
#define INTMUON_CHI2 3
#define INTMUON_STATUS 4
#define INTMUON_PLANE 5
#define INTMUON_ITRK 7
#define INTMUON_SIZE 8

/* Offsets for structure INTpmuon */
#define INTPMUON_TIME 0
#define INTPMUON_CHANNEL 1
#define INTPMUON_SIZE 2

/* Offsets for structure INThacclus */
#define INTHACCLUS_ENERGY 0
#define INTHACCLUS_X 1
#define INTHACCLUS_Y 2
#define INTHACCLUS_TIME 3
#define INTHACCLUS_BFRATIO 4
#define INTHACCLUS_SIZE 5

/* Offsets for structure INTSCDCHmult */
#define INTSCDCHMULT_MBXPLANEEFF 0
#define INTSCDCHMULT_L1TRK24EFF 6
#define INTSCDCHMULT_DCHSNOWERR 8
#define INTSCDCHMULT_MBXMULT 10
#define INTSCDCHMULT_TRK24ON 11
#define INTSCDCHMULT_SIZE 12

/* Offsets for structure INTPUtslice */
#define INTPUTSLICE_CHAN 0
#define INTPUTSLICE_SIZE 16

/* Offsets for structure INTMaChit */
#define INTMACHIT_COUNTER 0
#define INTMACHIT_PHEIGHT 1
#define INTMACHIT_TIME 2
#define INTMACHIT_PDSFLAG 3
#define INTMACHIT_SIZE 4

/* Offsets for structure INTsuperCmpEvent */
#define INTSUPERCMPEVENT_CMPSTATUS 0
#define INTSUPERCMPEVENT_FLAGCORR 1
#define INTSUPERCMPEVENT_CMPFILTER 2
#define INTSUPERCMPEVENT_DETSTATUS 3
#define INTSUPERCMPEVENT_RNDM 29
#define INTSUPERCMPEVENT_NEVT 102
#define INTSUPERCMPEVENT_TRIGWORD 103
#define INTSUPERCMPEVENT_TIMESTAMP 104
#define INTSUPERCMPEVENT_NTRIGBEF 105
#define INTSUPERCMPEVENT_TIMETOPREV 106
#define INTSUPERCMPEVENT_SPSPHASE 107
#define INTSUPERCMPEVENT_MAINSPHASE 108
#define INTSUPERCMPEVENT_SPSPHASERAW 109
#define INTSUPERCMPEVENT_MAINSPHASERAW 110
#define INTSUPERCMPEVENT_KLMONDNDT 111
#define INTSUPERCMPEVENT_QXDNDT 112
#define INTSUPERCMPEVENT_PU 113
#define INTSUPERCMPEVENT_NMCH 273
#define INTSUPERCMPEVENT_MCH 274
#define INTSUPERCMPEVENT_LKRDOWNSCALED 354
#define INTSUPERCMPEVENT_LKRENERGY 355
#define INTSUPERCMPEVENT_HACENERGY 356
#define INTSUPERCMPEVENT_NKABSTRAK 357
#define INTSUPERCMPEVENT_KABSTRAK 358
#define INTSUPERCMPEVENT_NTRACK 2608
#define INTSUPERCMPEVENT_TRACK 2609
#define INTSUPERCMPEVENT_NPMUON 4249
#define INTSUPERCMPEVENT_PMUON 4250
#define INTSUPERCMPEVENT_NHACCLUS 4362
#define INTSUPERCMPEVENT_HACCLUS 4363
#define INTSUPERCMPEVENT_NCLUSTER 4488
#define INTSUPERCMPEVENT_CLUSTER 4489
#define INTSUPERCMPEVENT_SCDCHEFFMULT 4989
#define INTSUPERCMPEVENT_TSPREV 5001
#define INTSUPERCMPEVENT_TSNEXT 5002
#define INTSUPERCMPEVENT_TWPREV 5003
#define INTSUPERCMPEVENT_TWNEXT 5004
#define INTSUPERCMPEVENT_SPAREINT 5005
#define INTSUPERCMPEVENT_SPAREFLOAT 5007
#define INTSUPERCMPEVENT_SIZE 5009

/* Offsets for structure INTsuperMcParticle */
#define INTSUPERMCPARTICLE_TYPE 0
#define INTSUPERMCPARTICLE_P 1
#define INTSUPERMCPARTICLE_PVERTEX 5
#define INTSUPERMCPARTICLE_DVERTEX 8
#define INTSUPERMCPARTICLE_SIZE 11

/* Offsets for structure INTsuperMcDecay */
#define INTSUPERMCDECAY_KTYPE 0
#define INTSUPERMCDECAY_DTYPE 1
#define INTSUPERMCDECAY_DVERTEX 2
#define INTSUPERMCDECAY_P 5
#define INTSUPERMCDECAY_SIZE 9

/* Offsets for structure INTsuperMcEvent */
#define INTSUPERMCEVENT_SIZE 0

#ifndef _COMPACT_H_RPCGEN

/* Compact constant definitions */
#define COMP_MAJOR_VER 7
#define COMP_MINOR_VER 3
#define COMP_PATCH 0
#define MAX_ARRAY_SIZE 70000
#define MAX_RNDM 1
#define MAX_PMB_TIMESLICES 16
#define MAX_PMB_CHANS 16
#define MAX_TAG_CHANS 60
#define MAX_KSM_HITS 20
#define MAX_AKL_HITS 100
#define MAX_TAG_HITS 15
#define MAX_DCH_HITS 64
#define MAX_DCH_TRACKS 40
#define MAX_DCH_CLUSTERS 100
#define MAX_DCH_VERTICES 100
#define MAX_DCH_HITS_NRO 1792
#define MAX_DCH_DOFS_NRO 45
#define MAX_POINT_CHAMBER 50
#define MAX_ACC_CHAMBER 50
#define MAX_HOD_HITS 50
#define MAX_HODNEUT_HITS 16
#define MAX_LKR_CLUST 50
#define MAX_KABES_HITS 50
#define MAX_KABES_TRACKS 50
#define MAX_NUT_KMU3 1
#define MAX_NHO_HITS 50
#define MAX_HAC_CLUST 50
#define MAX_MUV_HITS 50
#define MAX_PMUV_CHANS 56
#define MAX_PMUV_HITS 20
#define MAX_PHAC_CELLS 176
#define MAX_MC_SIM 5
#define MAX_MC_PARTICLES 20
#define MAX_MC_PLANES 20
#define MAX_L3_ACTIONS 30
#define MAX_L3_FILTERS 16
#define MAX_L3_STREAMS 10
#define MAX_L3_ERRORS 10
#define MAX_L3_PARTICLES 10
#define MAX_L3_TRIGHIST 10
#define MAX_EOB_DECERR 2000
#define MAX_TS_SCAL 100
#define MAX_L2TS_SCAL 20
#define MAX_ETASUMMARY 1
#define MAX_THM_DATA 90
#define MAX_SUMMARY 10
#define MAX_PROT 100
#define MAX_TRACK 40
#define MAX_MUON 12
#define MAX_PMUON 56
#define MAX_HACCLUS 25
#define MAX_CLUS 25
#define MAX_OVRFLW 50
#define MAX_ACCID 50
#define MAX_VERT 100
#define MAX_4VERT 12
#define MAX_VTX_TRACKS 7
#define MAX_PISA_SAMPLES 10
#define MAX_PISA_CNTSAMPLES 100
#define MAX_KABF_CHANNELS 20
#define MAX_KABF_TWINDOWS 60
#define MAX_KABF_TWLENGTH 300
#define SCF_EK 1000
#define SCF_PHASE 1000
#define SCF_EVTTIME 1000
#define SCF_MREC 100000
#define SCF_CTAU 1000
#define SCF_SPARE 1000
#define SCF_VTXX 100
#define SCF_VTXY 100
#define SCF_VTXZ 100
#define SCF_VTXCDA 100
#define SCF_VTXCOG 1000
#define SCF_VTXPHI 1000
#define SCF_VTXASP 10000
#define SCF_VTXTIME 1000
#define SCF_VTXPTSQ 10000000
#define SCF_AKSZ 100
#define SCF_ESC 10000
#define SCF_MPI0 100000
#define SCF_RELLI 1000
#define SCF_PI0MERR 100000
#define SCF_TAGTIME 1000
#define SCF_AKSTIME 1000
#define SCF_AKLTIME 1000
#define SCF_HACTIME 1000
#define SCF_TRKP 10000
#define SCF_TRKQL 1000
#define SCF_TRKX 1000
#define SCF_TRKY 1000
#define SCF_TRKZ 100
#define SCF_TRKDXDZ 100000
#define SCF_TRKDYDZ 100000
#define SCF_TRKTIME 100
#define SCF_TRKDDEAD 1000
#define SCF_TRKCHI2 1000
#define SCF_MUCHI2 1000
#define SCF_VTXCHI2 1000
#define SCF_PERR 10000
#define SCF_SIGXX 100000
#define SCF_SIGYY 100000
#define SCF_SIGDXDX 2147483647
#define SCF_SIGDYDY 2147483647
#define SCF_SIGXDX 2147483647
#define SCF_SIGXY 2147483647
#define SCF_SIGDXY 2147483647
#define SCF_SIGXDY 2147483647
#define SCF_SIGDXDY 2147483647
#define SCF_SIGYDY 2147483647
#define SCF_HODTIME 1000
#define SCF_NHODTIME 1000
#define SCF_LKRE 1000
#define SCF_LKRX 1000
#define SCF_LKRY 1000
#define SCF_LKRTIME 1000
#define SCF_ESPY 1000
#define SCF_EOVP 1000
#define SCF_HACE 1000
#define SCF_HACBF 1000
#define SCF_HACX 1000
#define SCF_HACY 1000
#define SCF_MUVTIME 1000
#define SCF_OVFLTIME 1000
#define SCF_OVFLX 100
#define SCF_OVFLY 100
#define SCF_KSMTIME 1000
#define SCF_KSMPH 100
#define SCF_DTARG 1000
#define SCF_PTPRIME 1000000
#define SCF_RNDMSPS 1000
#define SCF_RNDMMAIN 1000
#define SCF_RNDMTOVR 1000
#define SCF_INTENSMON 1000000
#define SCF_INTENSQXMON 100000000
#define SCF_INTENSMON98 1
#define SCF_INTENSQXMON98 1
#define SCF_KABMOM 10000
#define SCF_KABMOMERR 100000000
#define SCF_KABCHI2 1000
#define SCF_KABX 10000
#define SCF_KABY 10000
#define SCF_KABXUorD 10000
#define SCF_KABYUorD 10000
#define SCF_KABTIME 1000
#define SCF_KABDXDZ 2147483647
#define SCF_KABDYDZ 2147483647
#define SCF_KABXERR 100000000
#define SCF_KABYERR 100000000
#define SCF_KABTIMEERR 100000
#define SCF_KABSIGDXDX 100000000
#define SCF_KABSIGDYDY 100000000
#define SCF_AKLMIPS 100000
#define MAX_TRIGHIST 70000
#define MAX_PROCERROR 10000
#define MAX_BC_VECTOR 400
#define MAX_BC_VECTOR_01 800
#define KE3_SHW_SIZE 49
#define KE3_ADC_SIZE 45
#define ETA_SHW_SIZE 25
#define FHDR_STRUCT 1
#define BURST_STRUCT 2
#define CMPEVENT_STRUCT 3
#define SCMPEVENT_STRUCT 4
#define HCMPEVENT_STRUCT 5
#define UCMPEVENT_STRUCT 6
#define MCEVENT_STRUCT 7
#define SMCEVENT_STRUCT 8
#define KE3EVENT_STRUCT 9
#define EOB_STRUCT 10
#define FTLR_STRUCT 11
#define DCHEVENT_STRUCT 12
#define KMU3EVENT_STRUCT 13
#define SBURST_STRUCT 14
#define SEOB_STRUCT 15
#define ETAEVENT_STRUCT 16
#define HBURST_STRUCT 17
#define HEOB_STRUCT 19
#define KABEVENT_STRUCT 20
#define FEXTHDR_STRUCT 21
#define NO_BEAM 0
#define KL_BEAM 1
#define KS_BEAM 2
#define KSKL_BEAM 3
#define MUON_BEAM 4
#define MC_NMC 1
#define MC_NASIM 2
#define DATA_BURST 1
#define MC_BURST 2
#define CMP_FILE 0
#define SUPERCMP_FILE 1
#define HYPERCMP_FILE 2
#define ULTRACMP_FILE 3
#define MC_FILE 4
#define KE3_FILE 6
#define DCH_FILE 7
#define KMU3_FILE 8
#define SMC_FILE 9
#define ETA_FILE 10
#define KAB_FILE 11
#define MIXED_FILE 100
#define TAG_TS 1
#define AKS_TS 2
#define ANT_TS 3
#define DCH_TS 4
#define HOD_TS 5
#define LKR_TS 6
#define NUT_TS 7
#define HAC_TS 8
#define MUV_TS 9
#define NHO_TS 10
#define KSM_TS 11
#define MAX_TS 11
#define MAX_ANA_CHOD_COUNTER 20
#define MAX_ANA_TAG_PROTON 100
#define MAX_ANA_TAG_HIT 20

#endif
