import os.path
Import('env')
Import('*')

lenv = env.Clone()

lenv.SetRoot( root_dir )
lenv.SetBoost( boost_dir, boost_name, machine )
lenv.AddLibs( [
'tools', 
'reco', 
'dch',
] )
lenv.AddEvent( event_dir, 'event' )
lenv.SetYaml( yaml_dir, machine )
lenv.Append( CPPPATH = '../dch/dict' )


lenv.Append( CPPPATH = 'inc' )
lenv.SharedLibrary(
        target = 'conditions',
        source = Glob( 'src/*.cpp' )
        )
