#!/bin/bash
ldd build_bham/apps/hnureco \
		| ack  "build_bham" \
		| awk '{print $3} END {
			print "build_bham/apps/hnureco"
			print "build_bham/apps/k2pi_reco"
			print "build_bham/apps/file_description"
			print "input"
            print "batch_bham"
			print "scripts/bham_env.sh"
            print "local"
            print "tmp"
		}'  \
			| xargs tar -cvf ../binary/process.tar 
