#!/usr/bin/env python
import yaml
import os.path as osp

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

with open('input/reco/beam/cross_talk_mapping.yaml' ) as f:
    mapping = yaml.load(f) 

channel_lists = mapping['channel_lists']

for cl in channel_lists:
    print( 'period: {0}'.format( cl['period'] ) )
    for chan in cl['channels']:
        found = osp.isfile( osp.join( 'runlists/polroot/', chan + '.list' ) )
        if found:
            color = bcolors.OKGREEN
        else:
            color = bcolors.FAIL

        print( '{0}{1}: {2}{3}'.format(color,  chan, found, bcolors.ENDC ) )
