#!/bin/env python
from pyfiglet import Figlet
import argparse

#  ______ _       _      _   
# |  ____(_)     | |    | |  
# | |__   _  __ _| | ___| |_ 
# |  __| | |/ _` | |/ _ \ __|
# | |    | | (_| | |  __/ |_ 
# |_|    |_|\__, |_|\___|\__|
#            __/ |           
#           |___/            

f = Figlet()

def wrap( classname ):
    strings = []
    strings.append( '#ifndef ' + classname.upper() + '_HH' )
    strings.append( '#define ' + classname.upper() + '_HH' )
    strings.append( '#if 0' )
    strings.append( '/*' )
    figs = f.renderText( classname ).split('\n')
    for line in figs:
        strings.append( ' * ' + line )
    strings.append( '*/' )
    strings.append( '#endif')
    strings.append( 'namespace fn\n{')
    strings.append( 'class ' + classname + '\n{\n};\n}')
    strings.append( '#endif')
    return "\n".join( strings )

parser = argparse.ArgumentParser()
parser.add_argument( 'classname' )
args = parser.parse_args()

print( wrap( args.classname ) )
