#!/bin/bash
cat ./input/art/hnu_splash.txt

#commands
options=( \
    "./build_bham/apps/halo_subtract -m input/halo_sub/hsub.q11t.yaml    -o tdata/staging/halo_sub.q11t.root -l tdata/staging/log/halo_sub_log.q11t.root" \
    "./build_bham/apps/km2_subtract  -m input/km2_sub/halo_control.yaml  -o tdata/staging/km2_sub.q11t.root  -l tdata/staging/log/km2_sub_log.q11t.root" \
    )

select opt in "${options[@]}" "quit"
do
    if [ "$opt" = "quit" ]; then
        exit;
    fi
    eval $opt
    exit
done
