#!/usr/bin/env python
import os.path as osp

def print_plots( pre, sel, post, name, rebin ):
    return '- {{ path: {0}, name: {1}, rebin: {2} }}'.format( 
            osp.join( pre, sel, post), name, rebin )


sels = [
        '',
        "s33_0900_120_00_000", 
        "s33_0110_080_00_000", 
        "s33_0110_100_00_000", 
        "s33_0000_000_04_150",
        "s33_0000_000_08_037", ] 


plots = [
        ( 'hdm2_pi0', 'dm2_pi0', 1 ),
        ('hcda' , 'cda', 10 ), 
        ('hpt_' , 'dpt', 10 ), 
        ( 'lkr_dch_cmp/hdpop_' , 'dpop', 1 ),
        ( 'lkr_dch_cmp/hdpx' , 'dpx', 1 )]

for plot,dest,rebin in plots:
    for sel in sels:

        if sel:
            mysel = 'scatter_' + sel
        else:
            mysel  = ''

        folder = 'fit_eop_90'
        if 'cda' in dest :
            folder = 'fit_eop_90_no_cda'

        print( print_plots( folder , mysel,  plot, osp.join(dest, 'feop90_' + sel ) , rebin ) )
    print( '' )

