Import('env')
Import('*')

lenv = env.Clone()

lenv.SetRoot( root_dir )
lenv.SetBoost( boost_dir, boost_name )
lenv.SetYaml( yaml_dir )
lenv.AddEvent( event_dir, 'event' )

lenv.Append( CPPPATH = 'inc' )
lenv.SharedLibrary(
        target = 'tools',
        source = Glob( 'src/*.cpp' )
        )
