input_file: /afs/cern.ch/work/f/fnewson/hnu/gopher/data/thesis/muv_xy/all.muv_xy.root

channels:
    - { name: p5.data.q11t.v3, color : 634 }
    - { name : p5.km2.v2 , color : 602  }

plots:
    - name: raw_uw_p_full
      rebin: 2
      type: 2d
      hist_folder:  muv_eff_uw_r38_p_full
      passed_name: h_xy_passed
      total_name: h_xy_total

    - name: show_p_cutout
      rebin: 1
      type: 1d
      hist_folder: muv_eff_uw_r38_high_p_xycutout
      passed_name: h_p_passed
      total_name: h_p_total

    - name: measure_xy_cutout
      rebin: 1
      type: 2d
      hist_folder: muv_eff_uw_r38_high_p_xycutout
      passed_name: h_xy_passed
      total_name: h_xy_total

#   - name: v_tgt_geom_cut
#      rebin: 5
#      type: 1d
#      hist_folder: muon_eff_very_tgt_muv_pfull_eop
#      passed_name: h_p_passed
#      total_name: h_p_total
#
#    - name: pcorrp
#      rebin: 2
#      type: 2d
#      hist_folder: p_corr_restp
#      passed_name: h_xy_passed
#      total_name: h_xy_total


ratios:

#measure eff(xy) dependence for a cut-out region,
#using high momentum muons so we assume eff(p) =1.0 (flat)
    - source: measure_xy_cutout
      top: p5.data.q11t.v3
      bottom: p5.km2.v2
      dest: xyratio/cutout
      external: output/muv_eff_xy_cutout.root
      externalname: rat_xy

#    - source: pcorrp
#      top: p5.data.q11t.v3
#      bottom: p5.km2.v2
#      dest: pratio/pcorrestp
#      external: output/muv_eff_xy.root
