input_file: /afs/cern.ch/work/f/fnewson/hnu/gopher/data/thesis/muv_xy/all.muv_xy.root
rebin: 2
channel: p5.data.q11t.v3
hist_folder:  muon_eff_r38_p30_eop
passed_name: h_xy_passed
total_name: h_xy_total
