import os.path
Import('env')
Import('*')

lenv = env.Clone()

lenv.SetRoot( root_dir )
lenv.SetBoost( boost_dir, boost_name, machine )
lenv.AddLibs( [
'tools', 
'reco', 
'tracking',
'clusters',
'dch',
'muons',
] )
lenv.AddEvent( event_dir, 'event' )
lenv.SetYaml( yaml_dir, machine )

cint_builder = Builder( action = os.path.join(root_dir, 'bin', 'rootcint')+' -f $TARGET -c -p $SOURCES' )
lenv.Append( BUILDERS = { 'Dict' : cint_builder } )

dict_headers = [ Glob('dict/*.hh') ]
dict_sources = [ Glob('dict/*.cpp') ]
dict_headers.append( 'dict/LinkDef.h'  )

lenv.Dict( target = ['root/Km2EventDataDict.cpp', 'root/Km2EventDataDict.h'],
source = dict_headers)

km2data_sources = ['root/Km2EventDataDict.cpp']

target_sources = Glob( 'src/*.cpp')
target_sources.append( km2data_sources )

lenv.Append( CPPPATH = ['inc', 'root', 'dict', '../../'] )
lenv.SharedLibrary(
        target = 'km2',
        source = target_sources )

lenv.Replace( LIBS = [] )
lenv.SetRoot( root_dir)

lenv.SharedLibrary(
target = 'Km2EventData',
source = km2data_sources,
)
